"""Ambiguous and Out-Of-Scope Cases for Golden V3.

Contains 35 cases:
- 23 Genuinely Ambiguous Cases requiring clarification
- 12 Out-Of-Scope Cases across diverse non-retail domains that must safely decline without human review
"""

AMBIGUOUS_AND_OOS_CASES = [
    # --- 23 Ambiguous Cases (Clarification Required) ---
    {
        "customer_message": "I need help right now",
        "context": "CUSTOMER: I need help right now",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Ambiguous help request without context.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "What should I do next?",
        "context": "CUSTOMER: Hello\nBRAND: Hello! How can I assist you with Amazon today?\nCUSTOMER: What should I do next?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Ambiguous question without topic.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "It is simply not functioning",
        "context": "CUSTOMER: Trying to use the portal.\nBRAND: Which feature are you currently using?\nCUSTOMER: It is simply not functioning",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Vague unanchored complaint.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Still nothing",
        "context": "CUSTOMER: Checking on an update.\nBRAND: Could you tell me what you are waiting for?\nCUSTOMER: Still nothing",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Ambiguous status comment without order or issue context.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Can you fix this?",
        "context": "CUSTOMER: Having an issue.\nBRAND: Can you tell me what order or item you need help with?\nCUSTOMER: Can you fix this?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Vague request for resolution without specifying the issue.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Why did this happen?",
        "context": "CUSTOMER: I saw a change on my screen.\nBRAND: What change or message appeared?\nCUSTOMER: Why did this happen?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Unanchored question.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Need some assistance please",
        "context": "CUSTOMER: Need some assistance please",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Generic assistance request lacking detail.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Not happy with what just occurred",
        "context": "CUSTOMER: Not happy with what just occurred",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Emotional sentiment expression without incident specifics.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Can someone explain this?",
        "context": "CUSTOMER: Can someone explain this?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Ambiguous clarification inquiry.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Hi there, is customer service online right now?",
        "context": "CUSTOMER: Hi there, is customer service online right now?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Availability ping.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "I am so frustrated right now",
        "context": "CUSTOMER: I am so frustrated right now",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Emotional venting without operational details.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Amazon problem",
        "context": "CUSTOMER: Amazon problem",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Two-word ambiguous prompt.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "An unexpected error occurred on the screen",
        "context": "CUSTOMER: An unexpected error occurred on the screen",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Generic failure statement without details.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Check this out",
        "context": "CUSTOMER: Check this out",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Ambiguous message without attachment or reference.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Please review my situation",
        "context": "CUSTOMER: Customer service help needed.\nBRAND: Hi, what can I assist you with today?\nCUSTOMER: Please review my situation",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Broad request to review unspecified situation.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Is this normal?",
        "context": "CUSTOMER: Something seems strange.\nBRAND: Could you describe what you are seeing?\nCUSTOMER: Is this normal?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Question lacking subject matter or context.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Where do I look?",
        "context": "CUSTOMER: Where do I look?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Vague question requiring customer clarification.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Still waiting here",
        "context": "CUSTOMER: Still waiting here",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Waiting comment without subject.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Nothing makes sense",
        "context": "CUSTOMER: Nothing makes sense",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Subjective comment requiring clarification.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Can an agent look into this?",
        "context": "CUSTOMER: Can an agent look into this?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Agent intervention request with no details provided.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "I do not understand what happened",
        "context": "CUSTOMER: I do not understand what happened",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Unclear event description.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Can you clarify?",
        "context": "CUSTOMER: Can you clarify?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "General clarification request without prior topic.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Order issue",
        "context": "CUSTOMER: Hi\nBRAND: Hello, how can Amazon help you today?\nCUSTOMER: Order issue",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Extremely brief category tag without intent or order info.",
        "category": "AMBIGUOUS",
    },

    # --- 12 Out-Of-Scope Cases (Safe Auto-Handle / Decline) ---
    {
        "customer_message": "What will the weather be like in Chicago tomorrow afternoon?",
        "context": "CUSTOMER: What will the weather be like in Chicago tomorrow afternoon?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Weather forecast inquiry; outside retail domain.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "Can you calculate the compound interest on a $10,000 certificate of deposit at 4.5% annual yield?",
        "context": "CUSTOMER: Can you calculate the compound interest on a $10,000 certificate of deposit at 4.5% annual yield?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Banking compound interest calculation; outside retail domain.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "Can you write a Python function to reverse a singly linked list?",
        "context": "CUSTOMER: Can you write a Python function to reverse a singly linked list?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Software engineering programming task; outside domain.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "I have a sharp pain in my lower back, what medication should I take?",
        "context": "CUSTOMER: I have a sharp pain in my lower back, what medication should I take?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Medical diagnosis and pharmaceutical advice; outside domain.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "Can you explain the difference between a trademark and a patent under US copyright law?",
        "context": "CUSTOMER: Can you explain the difference between a trademark and a patent under US copyright law?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Legal intellectual property advice; outside domain.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "How do I calculate depreciation on rental property for my federal tax return?",
        "context": "CUSTOMER: How do I calculate depreciation on rental property for my federal tax return?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Income tax accounting advice; outside domain.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "What are the best tourist attractions to visit during a weekend trip to Tokyo?",
        "context": "CUSTOMER: What are the best tourist attractions to visit during a weekend trip to Tokyo?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "General travel tourism guide inquiry; outside domain.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "How do I make a classic French bechamel sauce from scratch with butter and flour?",
        "context": "CUSTOMER: How do I make a classic French bechamel sauce from scratch with butter and flour?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Culinary recipe instructions; outside domain.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "Can you help me troubleshoot why my custom gaming PC keeps blue-screening with memory management errors in Windows 11?",
        "context": "CUSTOMER: Can you help me troubleshoot why my custom gaming PC keeps blue-screening with memory management errors in Windows 11?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "General PC operating system troubleshooting; outside domain.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "Who was the prime minister of the United Kingdom during the Battle of Trafalgar in 1805?",
        "context": "CUSTOMER: Who was the prime minister of the United Kingdom during the Battle of Trafalgar in 1805?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Historical trivia inquiry; outside domain.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "How do I change the engine oil and oil filter on a 2018 Honda Civic sedan?",
        "context": "CUSTOMER: How do I change the engine oil and oil filter on a 2018 Honda Civic sedan?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Automotive mechanical maintenance inquiry; outside domain.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "Can you translate this paragraph from German into conversational Spanish for my pen pal?",
        "context": "CUSTOMER: Can you translate this paragraph from German into conversational Spanish for my pen pal?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "General language translation request; outside domain.",
        "category": "OUT_OF_SCOPE",
    },
]
