"""Carrier and Delivery Fulfillment Cases for Golden V3.

Contains 52 cases:
- 10 Carrier Misconduct & Delivery Refusal (Escalation)
- 10 Routine Carrier Instructions & Controls (Auto-Handle)
- 12 Delivery Delayed Cases (including repeated support variants and valid follow-ups)
- 10 Marked Delivered Not Received Cases
- 10 Where Is My Order & Tracking Edge Cases
"""

CARRIER_AND_DELIVERY_CASES = [
    # --- 10 Carrier Misconduct & Delivery Refusal (Escalates) ---
    {
        "customer_message": "The delivery driver refused to carry my air conditioner up a short flight of stairs despite explicit accessibility instructions and left it in the rain.",
        "context": "CUSTOMER: Complaint about delivery driver conduct today.\nBRAND: Could you describe what occurred with your delivery?\nCUSTOMER: The delivery driver refused to carry my air conditioner up a short flight of stairs despite explicit accessibility instructions and left it in the rain.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Driver refused reasonable delivery accommodation for accessibility.",
        "category": "CARRIER_MISCONDUCT",
    },
    {
        "customer_message": "Courier called from the street demanding that I walk two blocks to his van to pick up my heavy parcel because he didn't want to find street parking.",
        "context": "CUSTOMER: Issue with driver on delivery of order #112-9018247.\nBRAND: Did the carrier attempt delivery at your physical address?\nCUSTOMER: Courier called from the street demanding that I walk two blocks to his van to pick up my heavy parcel because he didn't want to find street parking.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Courier demanded customer walk down to vehicle for pickup.",
        "category": "CARRIER_MISCONDUCT",
    },
    {
        "customer_message": "The delivery driver became extremely belligerent, screamed at me, and rudely shouted profanities when I asked him to place the box behind the porch pillar.",
        "context": "CUSTOMER: Extremely unacceptable driver behavior outside my home.\nBRAND: What happened when the delivery driver arrived?\nCUSTOMER: The delivery driver became extremely belligerent, screamed at me, and rudely shouted profanities when I asked him to place the box behind the porch pillar.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Hostile, aggressive driver behavior with profanity.",
        "category": "CARRIER_MISCONDUCT",
    },
    {
        "customer_message": "Delivery person chucked my fragile computer monitor box over the 7-foot driveway gate, smashing it directly against the concrete driveway!",
        "context": "CUSTOMER: Reporting serious parcel damage caused by delivery driver.\nBRAND: How was the package handled upon arrival?\nCUSTOMER: Delivery person chucked my fragile computer monitor box over the 7-foot driveway gate, smashing it directly against the concrete driveway!",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Severe package mishandling; box thrown over fence.",
        "category": "CARRIER_MISCONDUCT",
    },
    {
        "customer_message": "Driver refused to deliver my order because I asked him to buzz the intercom number provided on the delivery instructions.",
        "context": "CUSTOMER: Courier refused to drop off parcel at my unit.\nBRAND: Were specific access codes provided for your building?\nCUSTOMER: Driver refused to deliver my order because I asked him to buzz the intercom number provided on the delivery instructions.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Delivery driver refused delivery over standard intercom instruction.",
        "category": "CARRIER_MISCONDUCT",
    },
    {
        "customer_message": "Courier refused to deliver essential medical supplies to my elderly mother's apartment door, dumping them on the wet curbside outside the building.",
        "context": "CUSTOMER: Terrible experience with the delivery courier today.\nBRAND: Can you describe what happened with the courier?\nCUSTOMER: Courier refused to deliver essential medical supplies to my elderly mother's apartment door, dumping them on the wet curbside outside the building.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Delivery refusal to door for vulnerable customer.",
        "category": "CARRIER_MISCONDUCT",
    },
    {
        "customer_message": "Driver aggressively banged on my front door, shouted rudely, and demanded a cash tip before handing over the parcel.",
        "context": "CUSTOMER: Driver demanded extra payment at my doorstep.\nBRAND: Did the carrier driver specify why they requested payment?\nCUSTOMER: Driver aggressively banged on my front door, shouted rudely, and demanded a cash tip before handing over the parcel.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Extortionate behavior: driver demanded cash tip aggressively.",
        "category": "CARRIER_MISCONDUCT",
    },
    {
        "customer_message": "Courier refused entry through security desk despite being provided an official guest badge and drove off, marking chronic delivery refusal.",
        "context": "CUSTOMER: Commercial delivery failed today.\nBRAND: Did security grant the carrier authorized facility access?\nCUSTOMER: Courier refused entry through security desk despite being provided an official guest badge and drove off, marking chronic delivery refusal.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Unreasonable carrier refusal to enter authorized facility.",
        "category": "CARRIER_MISCONDUCT",
    },
    {
        "customer_message": "Driver forged my signature on a high-value laptop delivery while I was away at work, leaving the package exposed on the sidewalk.",
        "context": "CUSTOMER: Signature verification discrepancy on delivery.\nBRAND: Did tracking show signed by resident?\nCUSTOMER: Driver forged my signature on a high-value laptop delivery while I was away at work, leaving the package exposed on the sidewalk.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Driver forged signature on signature-required high value item.",
        "category": "CARRIER_MISCONDUCT",
    },
    {
        "customer_message": "Delivery agent refused to complete delivery, telling me over the phone to come down to the parking lot or he would take it back to the hub.",
        "context": "CUSTOMER: Driver refused to come to the building.\nBRAND: Did you speak directly with the courier?\nCUSTOMER: Delivery agent refused to complete delivery, telling me over the phone to come down to the parking lot or he would take it back to the hub.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Delivery refusal ultimatum demanding customer meet driver.",
        "category": "CARRIER_MISCONDUCT",
    },

    # --- 10 Routine Carrier Instructions & Controls (Auto-Handle) ---
    {
        "customer_message": "Please add gate access code #5521 for the Amazon logistics delivery driver.",
        "context": "CUSTOMER: Adding access information for delivery today.\nBRAND: What gate code or entry instructions would you like provided?\nCUSTOMER: Please add gate access code #5521 for the Amazon logistics delivery driver.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Routine gate code instructions.",
        "category": "ROUTINE_CARRIER",
    },
    {
        "customer_message": "Can I request that packages be placed inside the screened back porch rather than the front steps?",
        "context": "CUSTOMER: Delivery location preference question.\nBRAND: Are you looking to update default delivery preferences for your address?\nCUSTOMER: Can I request that packages be placed inside the screened back porch rather than the front steps?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Routine delivery preference request.",
        "category": "ROUTINE_CARRIER",
    },
    {
        "customer_message": "The UPS driver was exceptionally courteous and careful with our glass shipment today, please pass along our appreciation.",
        "context": "CUSTOMER: The UPS driver was exceptionally courteous and careful with our glass shipment today, please pass along our appreciation.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Positive carrier feedback without escalation.",
        "category": "ROUTINE_CARRIER",
    },
    {
        "customer_message": "Where can I provide instructions to ring the front doorbell upon parcel arrival?",
        "context": "CUSTOMER: Notification instruction inquiry.\nBRAND: Do you want this noted on a specific order or for all future deliveries?\nCUSTOMER: Where can I provide instructions to ring the front doorbell upon parcel arrival?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Question regarding where to add doorbell instruction.",
        "category": "ROUTINE_CARRIER",
    },
    {
        "customer_message": "How do I contact the local carrier facility to arrange an evening delivery window?",
        "context": "CUSTOMER: Need to adjust delivery timing with courier.\nBRAND: Has your order already been assigned to a local carrier facility?\nCUSTOMER: How do I contact the local carrier facility to arrange an evening delivery window?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Inquiry on contacting carrier for delivery window scheduling.",
        "category": "ROUTINE_CARRIER",
    },
    {
        "customer_message": "Can you leave a delivery note asking the driver not to block the driveway gate when dropping off packages?",
        "context": "CUSTOMER: Can you leave a delivery note asking the driver not to block the driveway gate when dropping off packages?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Standard delivery placement request.",
        "category": "ROUTINE_CARRIER",
    },
    {
        "customer_message": "What carrier is handling transit for my package departing from the Phoenix fulfillment center?",
        "context": "CUSTOMER: Checking shipment courier information.\nBRAND: Have you viewed your shipment confirmation email?\nCUSTOMER: What carrier is handling transit for my package departing from the Phoenix fulfillment center?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Carrier identity inquiry.",
        "category": "ROUTINE_CARRIER",
    },
    {
        "customer_message": "I want to add access instructions for our apartment call box code #890 for future Amazon deliveries.",
        "context": "CUSTOMER: I want to add access instructions for our apartment call box code #890 for future Amazon deliveries.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Call box access code update.",
        "category": "ROUTINE_CARRIER",
    },
    {
        "customer_message": "Please notify the delivery partner that there is a friendly dog in the fenced front yard so they do not get frightened.",
        "context": "CUSTOMER: Please notify the delivery partner that there is a friendly dog in the fenced front yard so they do not get frightened.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Routine pet safety note for courier.",
        "category": "ROUTINE_CARRIER",
    },
    {
        "customer_message": "Where do I update my default delivery instructions on the Amazon mobile app?",
        "context": "CUSTOMER: Where do I update my default delivery instructions on the Amazon mobile app?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Self-service delivery instruction settings inquiry.",
        "category": "ROUTINE_CARRIER",
    },

    # --- 12 Delivery Delayed Cases ---
    {
        "customer_message": "I've been passed between six different representatives across multiple calls regarding my overdue delivery and nobody has provided a straight answer!",
        "context": "CUSTOMER: Following up on overdue package.\nBRAND: Have you checked the latest carrier scan update?\nCUSTOMER: I've been passed between six different representatives across multiple calls regarding my overdue delivery and nobody has provided a straight answer!",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Repeated failed support across multiple transfers on delayed shipment.",
        "category": "REPEATED_SUPPORT",
    },
    {
        "customer_message": "Called support across 5 attempts over 10 days for my delayed medication and nobody has been able to sort this out.",
        "context": "CUSTOMER: Chronic delay on urgent medication order.\nBRAND: What did previous representatives advise regarding shipment status?\nCUSTOMER: Called support across 5 attempts over 10 days for my delayed medication and nobody has been able to sort this out.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Chronic unresolved delivery delay after five support calls.",
        "category": "REPEATED_SUPPORT",
    },
    {
        "customer_message": "A supervisor promised a guaranteed callback within 4 hours regarding my delayed furniture that never happened and now it's been 3 days.",
        "context": "CUSTOMER: Awaiting promised support escalation callback.\nBRAND: Did the previous supervisor provide a ticket reference number?\nCUSTOMER: A supervisor promised a guaranteed callback within 4 hours regarding my delayed furniture that never happened and now it's been 3 days.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Broken callback window following repeated delays.",
        "category": "REPEATED_SUPPORT",
    },
    {
        "customer_message": "I've chased support repeatedly about my delayed parcel and keep getting bounced between courier and Amazon with no resolution.",
        "context": "CUSTOMER: Following up on overdue package.\nBRAND: Have you checked with the carrier depot?\nCUSTOMER: I've chased support repeatedly about my delayed parcel and keep getting bounced between courier and Amazon with no resolution.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Repeated circular referrals without support resolution.",
        "category": "REPEATED_SUPPORT",
    },
    {
        "customer_message": "My package was expected yesterday by 8 PM and still hasn't arrived. Can you check status?",
        "context": "CUSTOMER: Inquiry regarding order #113-8821940.\nBRAND: Did tracking indicate out for delivery yesterday?\nCUSTOMER: My package was expected yesterday by 8 PM and still hasn't arrived. Can you check status?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Standard late delivery check.",
        "category": "DELIVERY_DELAY",
    },
    {
        "customer_message": "Tracking shows 'Delayed in transit'. What causes transit delays in winter weather conditions?",
        "context": "CUSTOMER: Tracking shows 'Delayed in transit'. What causes transit delays in winter weather conditions?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer checked tracking and asks informational question about weather delay.",
        "category": "DELIVERY_DELAY",
    },
    {
        "customer_message": "My shipment is past the promised guaranteed delivery date. When am I eligible to request a refund or replacement?",
        "context": "CUSTOMER: My shipment is past the promised guaranteed delivery date. When am I eligible to request a refund or replacement?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Routine inquiry about delay compensation and replacement eligibility.",
        "category": "DELIVERY_DELAY",
    },
    {
        "customer_message": "Package has been stuck at the regional distribution center for 3 days without movement.",
        "context": "CUSTOMER: Package transit inquiry.\nBRAND: Has the estimated delivery date passed?\nCUSTOMER: Package has been stuck at the regional distribution center for 3 days without movement.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Stalled transit tracking inquiry.",
        "category": "DELIVERY_DELAY",
    },
    {
        "customer_message": "Ordered with same-day shipping this morning but tracking indicates it won't arrive until tomorrow afternoon.",
        "context": "CUSTOMER: Same-day shipping timeline question.\nBRAND: Did you select same-day checkout before the daily cutoff window?\nCUSTOMER: Ordered with same-day shipping this morning but tracking indicates it won't arrive until tomorrow afternoon.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Same day shipping delay inquiry.",
        "category": "DELIVERY_DELAY",
    },
    {
        "customer_message": "I already checked the tracking website, why is my parcel delayed in transit?",
        "context": "CUSTOMER: Inquiry regarding order #112-9847120.\nBRAND: Have you reviewed the carrier tracking portal today?\nCUSTOMER: I already checked the tracking website, why is my parcel delayed in transit?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Valid follow-up question after verifying tracking; not an inconsistency.",
        "category": "STATE_CONSISTENCY_CONTROL",
    },
    {
        "customer_message": "I contacted support yesterday once and they told me it might arrive today, but still hasn't shown up.",
        "context": "CUSTOMER: Delivery delay follow-up.\nBRAND: What advice did our representative provide on yesterday's contact?\nCUSTOMER: I contacted support yesterday once and they told me it might arrive today, but still hasn't shown up.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Single prior contact negative control; should NOT escalate.",
        "category": "SINGLE_CONTACT_CONTROL",
    },
    {
        "customer_message": "Tracking says delivery appointment scheduled for Tuesday. Does that mean I must be home to sign?",
        "context": "CUSTOMER: Tracking says delivery appointment scheduled for Tuesday. Does that mean I must be home to sign?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer asks what appointment status implies.",
        "category": "DELIVERY_DELAY",
    },

    # --- 10 Marked Delivered Not Received Cases ---
    {
        "customer_message": "Tracking says delivered to mailbox at 2 PM but my mailbox is completely empty.",
        "context": "CUSTOMER: Package delivery scan issue.\nBRAND: Have you verified the delivery confirmation details in Your Orders?\nCUSTOMER: Tracking says delivered to mailbox at 2 PM but my mailbox is completely empty.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Delivered to mailbox false scan inquiry.",
        "category": "DELIVERY_DISPUTE",
    },
    {
        "customer_message": "App shows parcel left in resident lobby, but building management confirmed no deliveries arrived today.",
        "context": "CUSTOMER: Delivery location dispute on order #114-7721849.\nBRAND: Did the delivery photo show the lobby mail table?\nCUSTOMER: App shows parcel left in resident lobby, but building management confirmed no deliveries arrived today.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Lobby delivery scanned but not present.",
        "category": "DELIVERY_DISPUTE",
    },
    {
        "customer_message": "Marked as delivered handed to resident, but I was at work all afternoon and nobody was home.",
        "context": "CUSTOMER: Order status says handed to resident.\nBRAND: Could a family member or neighbor have accepted it on your behalf?\nCUSTOMER: Marked as delivered handed to resident, but I was at work all afternoon and nobody was home.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Handed to resident status dispute.",
        "category": "DELIVERY_DISPUTE",
    },
    {
        "customer_message": "Delivery photo shows a completely different front door with green trim; that is not my house.",
        "context": "CUSTOMER: Delivery photo shows a completely different front door with green trim; that is not my house.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Misdelivery proven by delivery photo mismatch.",
        "category": "DELIVERY_DISPUTE",
    },
    {
        "customer_message": "Received notification that order was delivered 10 minutes ago, checked front porch immediately and nothing is there.",
        "context": "CUSTOMER: Received notification that order was delivered 10 minutes ago, checked front porch immediately and nothing is there.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Premature carrier delivery scan inquiry.",
        "category": "DELIVERY_DISPUTE",
    },
    {
        "customer_message": "Carrier marked parcel delivered yesterday. Checked with neighbors and building security, no sign of it.",
        "context": "CUSTOMER: 24 hours passed since delivery scan.\nBRAND: Have you checked alternative drop locations around your property?\nCUSTOMER: Carrier marked parcel delivered yesterday. Checked with neighbors and building security, no sign of it.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "24-hour post-delivery scan search completed.",
        "category": "DELIVERY_DISPUTE",
    },
    {
        "customer_message": "Driver photo shows package dropped near public street sidewalk instead of my door and it's gone.",
        "context": "CUSTOMER: Delivery photo inspection on missing package.\nBRAND: Was the package left inside your front gate perimeter?\nCUSTOMER: Driver photo shows package dropped near public street sidewalk instead of my door and it's gone.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Unsafe sidewalk drop resulted in missing parcel.",
        "category": "DELIVERY_DISPUTE",
    },
    {
        "customer_message": "I called support 3 times already about this order marked delivered that never arrived, and each rep hung up or transferred me!",
        "context": "CUSTOMER: Calling about missing order marked delivered.\nBRAND: Did previous agents open an investigation with the logistics carrier?\nCUSTOMER: I called support 3 times already about this order marked delivered that never arrived, and each rep hung up or transferred me!",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Repeated support failure with hang-ups on missing delivery.",
        "category": "REPEATED_SUPPORT",
    },
    {
        "customer_message": "Package shows delivered to parcel locker, but the access code provided does not open any locker door.",
        "context": "CUSTOMER: Package shows delivered to parcel locker, but the access code provided does not open any locker door.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Locker barcode failure on delivered order.",
        "category": "DELIVERY_DISPUTE",
    },
    {
        "customer_message": "Status says delivered to garage via Key Delivery, but my garage door was never opened today.",
        "context": "CUSTOMER: Status says delivered to garage via Key Delivery, but my garage door was never opened today.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Key In-Garage delivery status dispute.",
        "category": "DELIVERY_DISPUTE",
    },

    # --- 10 Where Is My Order & Tracking Edge Cases ---
    {
        "customer_message": "Where can I find the tracking number for my order dispatched this morning?",
        "context": "CUSTOMER: Tracking lookup assistance needed.\nBRAND: Have you received your dispatch confirmation notification?\nCUSTOMER: Where can I find the tracking number for my order dispatched this morning?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Asking where tracking number is located; NOT tracking checked.",
        "category": "TRACKING_EDGE_CASE",
    },
    {
        "customer_message": "How do I check the live map tracking for my package that is out for delivery today?",
        "context": "CUSTOMER: How do I check the live map tracking for my package that is out for delivery today?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Live map tracking feature inquiry.",
        "category": "TRACKING_EDGE_CASE",
    },
    {
        "customer_message": "Can you tell me the current location of order #114-8829103-9920194?",
        "context": "CUSTOMER: Inquiring about shipping progress.\nBRAND: Could you provide the order ID you want tracked?\nCUSTOMER: Can you tell me the current location of order #114-8829103-9920194?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Standard package location inquiry.",
        "category": "WHERE_IS_ORDER",
    },
    {
        "customer_message": "Tracking says departed carrier facility, what does that mean in terms of delivery timeframe?",
        "context": "CUSTOMER: Checking on order tracking status.\nBRAND: Have you looked at the tracking timeline?\nCUSTOMER: Tracking says departed carrier facility, what does that mean in terms of delivery timeframe?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Explanation request on tracking milestone; tracking verified.",
        "category": "TRACKING_EDGE_CASE",
    },
    {
        "customer_message": "Where do I find my order tracking link in the Amazon shopping app?",
        "context": "CUSTOMER: Where do I find my order tracking link in the Amazon shopping app?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Asking where tracking link is located; NOT tracking checked.",
        "category": "TRACKING_EDGE_CASE",
    },
    {
        "customer_message": "I checked the carrier page and it still says shipping label created. Has Amazon handed it over yet?",
        "context": "CUSTOMER: I checked the carrier page and it still says shipping label created. Has Amazon handed it over yet?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer verified carrier page; inquiring on fulfillment handover.",
        "category": "TRACKING_EDGE_CASE",
    },
    {
        "customer_message": "Can you provide an estimated arrival time for my package scheduled to arrive today?",
        "context": "CUSTOMER: Can you provide an estimated arrival time for my package scheduled to arrive today?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Estimated delivery window query.",
        "category": "WHERE_IS_ORDER",
    },
    {
        "customer_message": "What carrier tracking service is used for international delivery to Canada?",
        "context": "CUSTOMER: What carrier tracking service is used for international delivery to Canada?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "International carrier tracking carrier inquiry.",
        "category": "WHERE_IS_ORDER",
    },
    {
        "customer_message": "Order shows shipped three days ago, when will detailed tracking scans appear?",
        "context": "CUSTOMER: Dispatch scan question.\nBRAND: Has the carrier scanned the parcel at the regional sorting hub?\nCUSTOMER: Order shows shipped three days ago, when will detailed tracking scans appear?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Initial tracking update lag query.",
        "category": "WHERE_IS_ORDER",
    },
    {
        "customer_message": "I'm checking where my order is. The estimated date is next Friday, just wanted to see if it dispatched from warehouse.",
        "context": "CUSTOMER: I'm checking where my order is. The estimated date is next Friday, just wanted to see if it dispatched from warehouse.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Dispatch verification before estimated delivery.",
        "category": "WHERE_IS_ORDER",
    },
]
