"""Multi-Intent Cases for Golden V3.

Contains 20 realistic multi-intent combinations:
- Validated against frozen Taxonomy V1 leaf intents
- Balanced between escalation (misconduct, security, repeated support) and safe auto-handling
- Multi-turn and single-turn realistic conversations
"""

MULTI_INTENT_CASES = [
    {
        "customer_message": "My package is 4 days late, and when the driver finally showed up he refused to walk to the porch and yelled insults at me from the street!",
        "context": "CUSTOMER: Terrible delivery experience with courier.\nBRAND: Did the package eventually get dropped at your residence?\nCUSTOMER: My package is 4 days late, and when the driver finally showed up he refused to walk to the porch and yelled insults at me from the street!",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED|CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Delayed package combined with verbal aggression and delivery refusal.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "I received the wrong blender model, returned it last week, and now I need to check when the refund will hit my credit card.",
        "context": "CUSTOMER: Following up on incorrect item return.\nBRAND: Has the item been scanned as received at our returns hub?\nCUSTOMER: I received the wrong blender model, returned it last week, and now I need to check when the refund will hit my credit card.",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING|RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED|REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Wrong item return followed by refund status tracking.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "The microwave arrived with a shattered glass door, and the UPS courier missed the scheduled return pickup appointment today.",
        "context": "CUSTOMER: The microwave arrived with a shattered glass door, and the UPS courier missed the scheduled return pickup appointment today.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM|RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Damaged goods return coupled with missed courier collection.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "There is an unexpected $14.99 charge on my credit card from Amazon Prime even though I cancelled my subscription last month.",
        "context": "CUSTOMER: Unrecognized subscription debit on statement.\nBRAND: Did you receive a confirmation email when you cancelled Prime?\nCUSTOMER: There is an unexpected $14.99 charge on my credit card from Amazon Prime even though I cancelled my subscription last month.",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME|REFUNDS_AND_BILLING",
        "intents": "PRIME_MEMBERSHIP_MANAGEMENT|UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "primary_intent": "UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Post-cancellation Prime membership renewal charge dispute.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "I cancelled order #112-9840192 yesterday prior to shipment, how long until the authorization hold drops from my debit card?",
        "context": "CUSTOMER: Bank debit hold question after order cancellation.\nBRAND: Was the cancellation confirmed before warehouse fulfillment?\nCUSTOMER: I cancelled order #112-9840192 yesterday prior to shipment, how long until the authorization hold drops from my debit card?",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT|REFUNDS_AND_BILLING",
        "intents": "CANCEL_ORDER_REQUEST|REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Pre-shipment cancellation refund release timeline.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "I cannot log into my account and just received a text alert about an unauthorized $500 order placed from an unknown device!",
        "context": "CUSTOMER: I cannot log into my account and just received a text alert about an unauthorized $500 order placed from an unknown device!",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY|REFUNDS_AND_BILLING",
        "intents": "ACCOUNT_LOGIN_ISSUES|UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Account lockout coinciding with unauthorized high-value fraudulent purchase.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "Can you tell me where my parcel currently is, and is it still possible to change the delivery address to my office?",
        "context": "CUSTOMER: Following up on recent shipment.\nBRAND: Have you checked the latest dispatch tracking scan?\nCUSTOMER: Can you tell me where my parcel currently is, and is it still possible to change the delivery address to my office?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT|ORDER_MANAGEMENT",
        "intents": "WHERE_IS_MY_ORDER|MODIFY_ORDER_DETAILS",
        "primary_intent": "MODIFY_ORDER_DETAILS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Tracking inquiry paired with destination address update request.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "Order was marked delivered, but neighbors saw the courier throw the package into an open truck and drive off with it!",
        "context": "CUSTOMER: Order was marked delivered, but neighbors saw the courier throw the package into an open truck and drive off with it!",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED|CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "False delivery scan combined with courier theft/mishandling.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "This birthday gift was supposed to arrive two days ago and is now delayed until next week. I want to cancel it immediately.",
        "context": "CUSTOMER: Delayed birthday present inquiry.\nBRAND: Would you like us to look into expedited replacement options?\nCUSTOMER: This birthday gift was supposed to arrive two days ago and is now delayed until next week. I want to cancel it immediately.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT|ORDER_MANAGEMENT",
        "intents": "DELIVERY_DELAYED|CANCEL_ORDER_REQUEST",
        "primary_intent": "CANCEL_ORDER_REQUEST",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Severe delivery delay motivating order cancellation.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "Sent the wrong size shoes on Monday, requested replacement, and the replacement shipment is now also delayed in transit.",
        "context": "CUSTOMER: Checking status on shoe exchange.\nBRAND: Do you have the tracking ID for the replacement package?\nCUSTOMER: Sent the wrong size shoes on Monday, requested replacement, and the replacement shipment is now also delayed in transit.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT|RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED|DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Replacement item experiencing shipping delays.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "My Prime Video app says I need to renew Prime, but my Prime membership annual receipt shows active through December.",
        "context": "CUSTOMER: Digital streaming app billing prompt.\nBRAND: Have you checked your active subscriptions under Account Settings?\nCUSTOMER: My Prime Video app says I need to renew Prime, but my Prime membership annual receipt shows active through December.",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "DIGITAL_CONTENT_ACCESS|PRIME_MEMBERSHIP_MANAGEMENT",
        "primary_intent": "PRIME_MEMBERSHIP_MANAGEMENT",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Digital streaming entitlement mismatch against active Prime subscription.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "I have contacted support 4 separate times about this cracked soundbar and each representative transfers me without an RMA label!",
        "context": "CUSTOMER: I have contacted support 4 separate times about this cracked soundbar and each representative transfers me without an RMA label!",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM|RETURN_PICKUP_ISSUE",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Four unhelpful support transfers trying to return damaged electronics.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "Saw two identical charges for $89 on my statement for order #111-9201948, please remove the duplicate charge.",
        "context": "CUSTOMER: Double charge noticed on bank statement.\nBRAND: Did you receive two distinct order confirmation numbers?\nCUSTOMER: Saw two identical charges for $89 on my statement for order #111-9201948, please remove the duplicate charge.",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT|REFUNDS_AND_BILLING",
        "intents": "UNRECOGNIZED_OR_DUPLICATE_CHARGE|MODIFY_ORDER_DETAILS",
        "primary_intent": "UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Duplicate billing transaction on single order.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "I've reached out to customer support across 4 attempts regarding a missing order marked delivered and nobody has resolved this.",
        "context": "CUSTOMER: I've reached out to customer support across 4 attempts regarding a missing order marked delivered and nobody has resolved this.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED|WHERE_IS_MY_ORDER",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Chronic missing package dispute after four unsuccessful contacts.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "Where is my package currently located, and can you provide gate instructions for the delivery driver?",
        "context": "CUSTOMER: Checking delivery progress for incoming parcel.\nBRAND: Have you reviewed the delivery tracker in Your Orders?\nCUSTOMER: Where is my package currently located, and can you provide gate instructions for the delivery driver?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER|CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Tracking check combined with gate code delivery instructions.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "The courier missed the return pickup yesterday, will this delay my refund processing timeline?",
        "context": "CUSTOMER: Return pickup didn't happen yesterday.\nBRAND: Did you reschedule via the returns center?\nCUSTOMER: The courier missed the return pickup yesterday, will this delay my refund processing timeline?",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING|RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE|REFUND_STATUS_INQUIRY",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Missed pickup collection impact on refund arrival.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "Shipment is delayed by 2 days, please update delivery note to leave it with the front desk receptionist upon arrival.",
        "context": "CUSTOMER: Shipment is delayed by 2 days, please update delivery note to leave it with the front desk receptionist upon arrival.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED|CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": False,
        "escalATION_reason": None,
        "notes": "Delay acknowledgment with reception drop instruction.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "I cancelled this order yesterday but my credit card shows a duplicate pending transaction charge.",
        "context": "CUSTOMER: I cancelled this order yesterday but my credit card shows a duplicate pending transaction charge.",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT|REFUNDS_AND_BILLING",
        "intents": "CANCEL_ORDER_REQUEST|UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "primary_intent": "UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Duplicate pre-authorization hold on cancelled purchase.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "Cannot log into my Kindle app on my iPad because it rejects my credentials, while the website works fine.",
        "context": "CUSTOMER: Cannot log into my Kindle app on my iPad because it rejects my credentials, while the website works fine.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY|DIGITAL_SERVICES_AND_PRIME",
        "intents": "ACCOUNT_LOGIN_ISSUES|DIGITAL_CONTENT_ACCESS",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Device specific digital application sign-in barrier.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "Driver brought the wrong heavy box, and when I pointed out the name mismatch he cursed at me and dumped it in my driveway anyway.",
        "context": "CUSTOMER: Courier delivered someone else's package abusively.\nBRAND: Did the delivery driver take the incorrect parcel back?\nCUSTOMER: Driver brought the wrong heavy box, and when I pointed out the name mismatch he cursed at me and dumped it in my driveway anyway.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT|RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED|CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Wrong item delivered accompanied by abusive driver misconduct.",
        "category": "MULTI_INTENT",
    },
]
