"""Orders, Prime, and Digital Services Cases for Golden V3.

Contains 23 cases:
- 6 Cancel Order Request Cases
- 5 Modify Order Details Cases
- 6 Prime Membership Management Cases
- 6 Digital Content Access Cases
"""

ORDERS_PRIME_DIGITAL_CASES = [
    # --- 6 Cancel Order Request Cases ---
    {
        "customer_message": "Need to cancel order #112-4019284-9920184 immediately before it prepares for shipment.",
        "context": "CUSTOMER: Need to cancel order #112-4019284-9920184 immediately before it prepares for shipment.",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "CANCEL_ORDER_REQUEST",
        "primary_intent": "CANCEL_ORDER_REQUEST",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Pre-shipment cancellation request with order ID.",
        "category": "ORDER_MANAGEMENT",
    },
    {
        "customer_message": "I placed an order accidentally 5 minutes ago, where is the cancel button in Your Orders?",
        "context": "CUSTOMER: Accidental order placed just now.\nBRAND: Have you checked the order status in Your Orders?\nCUSTOMER: I placed an order accidentally 5 minutes ago, where is the cancel button in Your Orders?",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "CANCEL_ORDER_REQUEST",
        "primary_intent": "CANCEL_ORDER_REQUEST",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Accidental order cancellation guidance.",
        "category": "ORDER_MANAGEMENT",
    },
    {
        "customer_message": "I purchased a winter jacket and leather gloves together, but I found gloves locally. How do I remove only the gloves while keeping the jacket order active?",
        "context": "CUSTOMER: I purchased a winter jacket and leather gloves together, but I found gloves locally. How do I remove only the gloves while keeping the jacket order active?",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "CANCEL_ORDER_REQUEST",
        "primary_intent": "CANCEL_ORDER_REQUEST",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Partial order item cancellation.",
        "category": "ORDER_MANAGEMENT",
    },
    {
        "customer_message": "Requested cancellation 2 hours ago but status still shows 'Cancellation Pending'. Did it go through?",
        "context": "CUSTOMER: Cancellation status inquiry.\nBRAND: Did you submit the request prior to the order entering dispatch preparation?\nCUSTOMER: Requested cancellation 2 hours ago but status still shows 'Cancellation Pending'. Did it go through?",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "CANCEL_ORDER_REQUEST",
        "primary_intent": "CANCEL_ORDER_REQUEST",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Cancellation pending verification.",
        "category": "ORDER_MANAGEMENT",
    },
    {
        "customer_message": "I contacted support 3 times trying to cancel an unshipped backordered item and reps keep saying they cannot cancel it!",
        "context": "CUSTOMER: I contacted support 3 times trying to cancel an unshipped backordered item and reps keep saying they cannot cancel it!",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "CANCEL_ORDER_REQUEST",
        "primary_intent": "CANCEL_ORDER_REQUEST",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Repeated support refusal to cancel unshipped backordered order.",
        "category": "REPEATED_SUPPORT",
    },
    {
        "customer_message": "How long after pressing cancel order will I receive the confirmation email from Amazon?",
        "context": "CUSTOMER: How long after pressing cancel order will I receive the confirmation email from Amazon?",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "CANCEL_ORDER_REQUEST",
        "primary_intent": "CANCEL_ORDER_REQUEST",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Cancellation email notification timing.",
        "category": "ORDER_MANAGEMENT",
    },

    # --- 5 Modify Order Details Cases ---
    {
        "customer_message": "I moved yesterday and need to update the delivery address on order #114-9920194-2201948 before it dispatches.",
        "context": "CUSTOMER: Address modification request.\nBRAND: What is the current status shown on the order details page?\nCUSTOMER: I moved yesterday and need to update the delivery address on order #114-9920194-2201948 before it dispatches.",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "MODIFY_ORDER_DETAILS",
        "primary_intent": "MODIFY_ORDER_DETAILS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Address modification on open unshipped order.",
        "category": "ORDER_MANAGEMENT",
    },
    {
        "customer_message": "Can I change the payment card used on an active order that hasn't shipped yet?",
        "context": "CUSTOMER: Updating payment details.\nBRAND: Has your payment already been authorized by your bank?\nCUSTOMER: Can I change the payment card used on an active order that hasn't shipped yet?",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "MODIFY_ORDER_DETAILS",
        "primary_intent": "MODIFY_ORDER_DETAILS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Payment method modification for open order.",
        "category": "ORDER_MANAGEMENT",
    },
    {
        "customer_message": "Need to update the delivery day to Saturday for my upcoming scheduled Amazon Day pantry order.",
        "context": "CUSTOMER: Scheduled delivery adjustment.\nBRAND: Are you managing your Amazon Day delivery settings?\nCUSTOMER: Need to update the delivery day to Saturday for my upcoming scheduled Amazon Day pantry order.",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "MODIFY_ORDER_DETAILS",
        "primary_intent": "MODIFY_ORDER_DETAILS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Amazon Day delivery slot change.",
        "category": "ORDER_MANAGEMENT",
    },
    {
        "customer_message": "Can I upgrade the shipping speed on an open order from standard to One-Day Delivery?",
        "context": "CUSTOMER: Can I upgrade the shipping speed on an open order from standard to One-Day Delivery?",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "MODIFY_ORDER_DETAILS",
        "primary_intent": "MODIFY_ORDER_DETAILS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Shipping speed modification inquiry.",
        "category": "ORDER_MANAGEMENT",
    },
    {
        "customer_message": "I already gave my new address details in chat earlier, why is it still showing the old address on my open order?",
        "context": "CUSTOMER: Updating shipping destination.\nBRAND: Have you verified the change under Your Orders?\nCUSTOMER: I already gave my new address details in chat earlier, why is it still showing the old address on my open order?",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "MODIFY_ORDER_DETAILS",
        "primary_intent": "MODIFY_ORDER_DETAILS",
        "state": "DETAILS_ALREADY_PROVIDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Follow-up on previously submitted address update.",
        "category": "STATE_CONSISTENCY_CONTROL",
    },

    # --- 6 Prime Membership Management Cases ---
    {
        "customer_message": "I was charged $139 for an annual Prime membership renewal that I did not intend to renew. Can I get a refund?",
        "context": "CUSTOMER: Prime membership charge inquiry.\nBRAND: Have any Prime benefits been used since the renewal date?\nCUSTOMER: I was charged $139 for an annual Prime membership renewal that I did not intend to renew. Can I get a refund?",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "PRIME_MEMBERSHIP_MANAGEMENT",
        "primary_intent": "PRIME_MEMBERSHIP_MANAGEMENT",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Prime auto-renewal fee refund request.",
        "category": "PRIME_MEMBERSHIP",
    },
    {
        "customer_message": "How do I turn off automatic renewal for my Prime student trial before it converts next week?",
        "context": "CUSTOMER: Student trial renewal management.\nBRAND: Are you looking to cancel before the trial period ends?\nCUSTOMER: How do I turn off automatic renewal for my Prime student trial before it converts next week?",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "PRIME_MEMBERSHIP_MANAGEMENT",
        "primary_intent": "PRIME_MEMBERSHIP_MANAGEMENT",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Prime student trial cancellation guidance.",
        "category": "PRIME_MEMBERSHIP",
    },
    {
        "customer_message": "My partner and I want to link our profiles so we both get free two-day dispatch under the family sharing feature. How do we set that up?",
        "context": "CUSTOMER: My partner and I want to link our profiles so we both get free two-day dispatch under the family sharing feature. How do we set that up?",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "PRIME_MEMBERSHIP_MANAGEMENT",
        "primary_intent": "PRIME_MEMBERSHIP_MANAGEMENT",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Amazon Household benefit sharing inquiry.",
        "category": "PRIME_MEMBERSHIP",
    },
    {
        "customer_message": "I have contacted support 4 times about an unauthorized Prime charge on my card and each rep promises a reversal that never happens!",
        "context": "CUSTOMER: I have contacted support 4 times about an unauthorized Prime charge on my card and each rep promises a reversal that never happens!",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "PRIME_MEMBERSHIP_MANAGEMENT",
        "primary_intent": "PRIME_MEMBERSHIP_MANAGEMENT",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Four failed contacts regarding promised Prime charge reversal.",
        "category": "REPEATED_SUPPORT",
    },
    {
        "customer_message": "What are the requirements and verification needed to qualify for Prime Access discounted membership?",
        "context": "CUSTOMER: What are the requirements and verification needed to qualify for Prime Access discounted membership?",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "PRIME_MEMBERSHIP_MANAGEMENT",
        "primary_intent": "PRIME_MEMBERSHIP_MANAGEMENT",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Prime Access qualifying guidelines question.",
        "category": "PRIME_MEMBERSHIP",
    },
    {
        "customer_message": "How do I switch my Prime billing from monthly $14.99 to the annual membership plan to save money?",
        "context": "CUSTOMER: How do I switch my Prime billing from monthly $14.99 to the annual membership plan to save money?",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "PRIME_MEMBERSHIP_MANAGEMENT",
        "primary_intent": "PRIME_MEMBERSHIP_MANAGEMENT",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Prime billing interval switch procedure.",
        "category": "PRIME_MEMBERSHIP",
    },

    # --- 6 Digital Content Access Cases ---
    {
        "customer_message": "Prime Video gives error code 7031 on my smart TV when trying to play any title.",
        "context": "CUSTOMER: Streaming video error on TV.\nBRAND: Does this error occur across all devices or only your smart TV?\nCUSTOMER: Prime Video gives error code 7031 on my smart TV when trying to play any title.",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "DIGITAL_CONTENT_ACCESS",
        "primary_intent": "DIGITAL_CONTENT_ACCESS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Prime Video playback error troubleshooting.",
        "category": "DIGITAL_CONTENT",
    },
    {
        "customer_message": "Purchased a Kindle ebook 30 minutes ago but it has not synchronized to my Paperwhite reader.",
        "context": "CUSTOMER: Kindle digital delivery question.\nBRAND: Have you performed a manual Sync and Check for Items on your device?\nCUSTOMER: Purchased a Kindle ebook 30 minutes ago but it has not synchronized to my Paperwhite reader.",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "DIGITAL_CONTENT_ACCESS",
        "primary_intent": "DIGITAL_CONTENT_ACCESS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Kindle ebook sync delivery troubleshooting.",
        "category": "DIGITAL_CONTENT",
    },
    {
        "customer_message": "Amazon Music Unlimited app says my subscription is inactive even though payment was billed yesterday.",
        "context": "CUSTOMER: Music subscription access issue.\nBRAND: Are you signed in with the same Amazon account used for billing?\nCUSTOMER: Amazon Music Unlimited app says my subscription is inactive even though payment was billed yesterday.",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "DIGITAL_CONTENT_ACCESS",
        "primary_intent": "DIGITAL_CONTENT_ACCESS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Music subscription entitlement sync failure.",
        "category": "DIGITAL_CONTENT",
    },
    {
        "customer_message": "Rented a movie on Prime Video by mistake, haven't started streaming it, can I cancel for a refund?",
        "context": "CUSTOMER: Video rental cancellation.\nBRAND: Have you pressed play or downloaded any portion of the title?\nCUSTOMER: Rented a movie on Prime Video by mistake, haven't started streaming it, can I cancel for a refund?",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "DIGITAL_CONTENT_ACCESS",
        "primary_intent": "DIGITAL_CONTENT_ACCESS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Accidental video rental cancellation request.",
        "category": "DIGITAL_CONTENT",
    },
    {
        "customer_message": "Can I download Kindle audiobooks for offline listening on my iPad without Wi-Fi connection?",
        "context": "CUSTOMER: Can I download Kindle audiobooks for offline listening on my iPad without Wi-Fi connection?",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "DIGITAL_CONTENT_ACCESS",
        "primary_intent": "DIGITAL_CONTENT_ACCESS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Kindle offline audiobook playback inquiry.",
        "category": "DIGITAL_CONTENT",
    },
    {
        "customer_message": "I contacted support 3 times about a missing digital movie code that never delivered to my library and nobody helped!",
        "context": "CUSTOMER: I contacted support 3 times about a missing digital movie code that never delivered to my library and nobody helped!",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "DIGITAL_CONTENT_ACCESS",
        "primary_intent": "DIGITAL_CONTENT_ACCESS",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Three failed support attempts for undelivered digital movie redemption code.",
        "category": "REPEATED_SUPPORT",
    },
]
