"""Returns and Refunds Cases for Golden V3.

Contains 42 cases:
- 12 Damaged or Defective Item Cases (including repeated support variants and controls)
- 12 Wrong Item Received Cases (including repeated transfer escalation and negative controls)
- 10 Return Pickup Issue Cases (including multiple failed pickups escalation)
- 8 Refund Status Inquiry Cases (including unfulfilled refund promises escalation)
"""

RETURNS_AND_REFUNDS_CASES = [
    # --- 12 Damaged or Defective Item Cases ---
    {
        "customer_message": "I have contacted support 4 separate times about this cracked television and every agent promises a replacement pickup that never happens!",
        "context": "CUSTOMER: Following up on damaged television replacement.\nBRAND: Have you received confirmation of the replacement dispatch?\nCUSTOMER: I have contacted support 4 separate times about this cracked television and every agent promises a replacement pickup that never happens!",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Four failed support contacts regarding replacement pickup for damaged TV.",
        "category": "REPEATED_SUPPORT",
    },
    {
        "customer_message": "I've tried getting help several times across 3 weeks for this defective blender and no resolution was offered by customer service.",
        "context": "CUSTOMER: Ongoing problem with non-functional kitchen appliance.\nBRAND: Did previous representatives initiate a warranty exchange?\nCUSTOMER: I've tried getting help several times across 3 weeks for this defective blender and no resolution was offered by customer service.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Repeated unsuccessful attempts to resolve defective appliance.",
        "category": "REPEATED_SUPPORT",
    },
    {
        "customer_message": "Received ceramic dinner set today but three of the bowls were completely shattered in transit.",
        "context": "CUSTOMER: Order damaged upon opening.\nBRAND: What specific items were broken inside the parcel?\nCUSTOMER: Received ceramic dinner set today but three of the bowls were completely shattered in transit.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Transit damage report for fragile dinnerware.",
        "category": "DAMAGED_ITEM",
    },
    {
        "customer_message": "Brand new cordless vacuum turns on for 5 seconds and immediately shuts off with a red battery error indicator.",
        "context": "CUSTOMER: Technical defect on newly delivered vacuum.\nBRAND: Have you performed a full overnight charge cycle?\nCUSTOMER: Brand new cordless vacuum turns on for 5 seconds and immediately shuts off with a red battery error indicator.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Defective electronics battery failure out of box.",
        "category": "DAMAGED_ITEM",
    },
    {
        "customer_message": "The shampoo bottle leaked all over the inside of the box, soaking and ruining the other book items.",
        "context": "CUSTOMER: Delivery arrived damaged.\nBRAND: Was the external shipping carton also compromised?\nCUSTOMER: The shampoo bottle leaked all over the inside of the box, soaking and ruining the other book items.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Liquid spill damage inside shipping parcel.",
        "category": "DAMAGED_ITEM",
    },
    {
        "customer_message": "My electric kettle arrived with a dent in the stainless steel base and doesn't boil water properly.",
        "context": "CUSTOMER: Appliance arrived damaged in box.\nBRAND: Does the unit heat water when plugged into a different outlet?\nCUSTOMER: My electric kettle arrived with a dent in the stainless steel base and doesn't boil water properly.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Physical dent and electrical defect on arrival.",
        "category": "DAMAGED_ITEM",
    },
    {
        "customer_message": "The smartphone screen has dead green vertical pixel lines straight out of the sealed box.",
        "context": "CUSTOMER: The smartphone screen has dead green vertical pixel lines straight out of the sealed box.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Display panel defect on new mobile phone.",
        "category": "DAMAGED_ITEM",
    },
    {
        "customer_message": "The wooden study desk has a deep gouge across the top surface. How do I get a replacement part sent?",
        "context": "CUSTOMER: Furniture package opened today.\nBRAND: Was the outer packaging carton pierced or torn?\nCUSTOMER: The wooden study desk has a deep gouge across the top surface. How do I get a replacement part sent?",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Cosmetic scratch on furniture requiring part replacement.",
        "category": "DAMAGED_ITEM",
    },
    {
        "customer_message": "Headphones only produce sound in the left ear cup; the right side is completely silent.",
        "context": "CUSTOMER: Headphones only produce sound in the left ear cup; the right side is completely silent.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Audio hardware defect.",
        "category": "DAMAGED_ITEM",
    },
    {
        "customer_message": "The glass vase arrived broken into dozens of sharp fragments. Can I get a refund without shipping broken glass back?",
        "context": "CUSTOMER: Glass shipment arrived shattered.\nBRAND: For safety reasons, please do not handle broken glass.\nCUSTOMER: The glass vase arrived broken into dozens of sharp fragments. Can I get a refund without shipping broken glass back?",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Safety waiver request for returning broken glassware.",
        "category": "DAMAGED_ITEM",
    },
    {
        "customer_message": "I contacted customer care yesterday once about the damaged lamp and was asked to upload photos, which I have completed.",
        "context": "CUSTOMER: I contacted customer care yesterday once about the damaged lamp and was asked to upload photos, which I have completed.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "DETAILS_ALREADY_PROVIDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Single support contact follow-up; photos provided.",
        "category": "SINGLE_CONTACT_CONTROL",
    },
    {
        "customer_message": "Opened the box for my gaming mouse and the scroll wheel is completely loose and rattling inside.",
        "context": "CUSTOMER: Opened the box for my gaming mouse and the scroll wheel is completely loose and rattling inside.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Mechanical failure on computer peripheral.",
        "category": "DAMAGED_ITEM",
    },

    # --- 12 Wrong Item Received Cases ---
    {
        "customer_message": "I've been passed from agent to agent five times trying to get the right textbook sent for my semester!",
        "context": "CUSTOMER: Urgent book exchange needed.\nBRAND: What did the last agent advise regarding the re-order?\nCUSTOMER: I've been passed from agent to agent five times trying to get the right textbook sent for my semester!",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Multiple circular transfers across 5 attempts for incorrect book.",
        "category": "REPEATED_SUPPORT",
    },
    {
        "customer_message": "Support promised someone would contact me within 24 hours regarding the wrong laptop shipped, but nobody did and it's been four days.",
        "context": "CUSTOMER: Awaiting callback on wrong computer delivery.\nBRAND: Do you have the prior support case ID handy?\nCUSTOMER: Support promised someone would contact me within 24 hours regarding the wrong laptop shipped, but nobody did and it's been four days.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Unfulfilled callback promise on high value wrong item.",
        "category": "REPEATED_SUPPORT",
    },
    {
        "customer_message": "Ordered men's size 11 running shoes but received size 7 in the box.",
        "context": "CUSTOMER: Wrong item received on order #111-8849102.\nBRAND: What size did you receive in the manufacturer packaging?\nCUSTOMER: Ordered men's size 11 running shoes but received size 7 in the box.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Incorrect footwear size shipped.",
        "category": "WRONG_ITEM",
    },
    {
        "customer_message": "I ordered an espresso coffee machine but received a box containing stainless steel cookware instead.",
        "context": "CUSTOMER: Incorrect parcel contents received.\nBRAND: What item was inside the package delivered today?\nCUSTOMER: I ordered an espresso coffee machine but received a box containing stainless steel cookware instead.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Completely different category merchandise received.",
        "category": "WRONG_ITEM",
    },
    {
        "customer_message": "The package label has my name, but the item inside is a baby stroller which I never ordered.",
        "context": "CUSTOMER: Received an unexpected shipment.\nBRAND: Does the shipping label display your Amazon order number?\nCUSTOMER: The package label has my name, but the item inside is a baby stroller which I never ordered.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Mismatched shipment contents.",
        "category": "WRONG_ITEM",
    },
    {
        "customer_message": "Ordered a 500GB SSD drive but received a 128GB version instead.",
        "context": "CUSTOMER: Computer component variant mismatch.\nBRAND: What model specification is printed on the barcode label?\nCUSTOMER: Ordered a 500GB SSD drive but received a 128GB version instead.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Lower capacity computer storage variant received.",
        "category": "WRONG_ITEM",
    },
    {
        "customer_message": "Received black blackout curtains instead of the beige color ordered for our nursery.",
        "context": "CUSTOMER: Received black blackout curtains instead of the beige color ordered for our nursery.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Color variant error on home furnishing.",
        "category": "WRONG_ITEM",
    },
    {
        "customer_message": "Box contained an air purifier filter replacement instead of the actual air purifier unit I paid for.",
        "context": "CUSTOMER: Incomplete or incorrect shipment received.\nBRAND: Does the packing slip indicate a multi-box shipment?\nCUSTOMER: Box contained an air purifier filter replacement instead of the actual air purifier unit I paid for.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Accessory sent instead of main electronic device.",
        "category": "WRONG_ITEM",
    },
    {
        "customer_message": "I received 2 copies of a history book instead of the board game ordered for family night.",
        "context": "CUSTOMER: I received 2 copies of a history book instead of the board game ordered for family night.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Wrong item fulfillment error.",
        "category": "WRONG_ITEM",
    },
    {
        "customer_message": "The shirt sent is extra large when my order receipt clearly specifies size medium.",
        "context": "CUSTOMER: The shirt sent is extra large when my order receipt clearly specifies size medium.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Apparel size discrepancy.",
        "category": "WRONG_ITEM",
    },
    {
        "customer_message": "I spoke with support earlier today and they generated an exchange, just confirming the label arrived in email.",
        "context": "CUSTOMER: I spoke with support earlier today and they generated an exchange, just confirming the label arrived in email.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Single support interaction confirmation; negative control.",
        "category": "SINGLE_CONTACT_CONTROL",
    },
    {
        "customer_message": "Received a pack of AA disposable batteries instead of the rechargeable battery charger kit.",
        "context": "CUSTOMER: Received a pack of AA disposable batteries instead of the rechargeable battery charger kit.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Wrong item replacement request.",
        "category": "WRONG_ITEM",
    },

    # --- 10 Return Pickup Issue Cases ---
    {
        "customer_message": "Courier failed the scheduled return pickup 4 separate times and customer care just reschedules without fixing the courier problem!",
        "context": "CUSTOMER: Ongoing failure with return pickup service.\nBRAND: Did the carrier leave any missed pickup door-tags?\nCUSTOMER: Courier failed the scheduled return pickup 4 separate times and customer care just reschedules without fixing the courier problem!",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Four consecutive missed pickups with failed support escalation.",
        "category": "REPEATED_SUPPORT",
    },
    {
        "customer_message": "I've spent days trying to get this mattress return picked up; driver never showed up across three separate appointments.",
        "context": "CUSTOMER: Bulky mattress return collection issue.\nBRAND: Have our logistics partners provided an updated pickup window?\nCUSTOMER: I've spent days trying to get this mattress return picked up; driver never showed up across three separate appointments.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Three missed bulky item pickup appointments.",
        "category": "REPEATED_SUPPORT",
    },
    {
        "customer_message": "Called support 3 times about courier not showing up for return pickup and each rep told me someone would call, but nobody called.",
        "context": "CUSTOMER: Checking on rescheduled return pickup.\nBRAND: What did previous agents confirm regarding carrier dispatch?\nCUSTOMER: Called support 3 times about courier not showing up for return pickup and each rep told me someone would call, but nobody called.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Unfulfilled support callback commitments on missed pickups.",
        "category": "REPEATED_SUPPORT",
    },
    {
        "customer_message": "UPS driver did not show up for my scheduled return pickup between 9 AM and 1 PM today.",
        "context": "CUSTOMER: Return pickup appointment status inquiry.\nBRAND: Was a return pickup window scheduled for this morning?\nCUSTOMER: UPS driver did not show up for my scheduled return pickup between 9 AM and 1 PM today.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "First missed return pickup appointment.",
        "category": "RETURN_PICKUP",
    },
    {
        "customer_message": "How do I print a return shipping label if I do not have a home printer?",
        "context": "CUSTOMER: How do I print a return shipping label if I do not have a home printer?",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Printerless return drop-off guidance.",
        "category": "RETURN_PICKUP",
    },
    {
        "customer_message": "The QR drop-off code generated for The UPS Store shows expired on my phone. How do I regenerate it?",
        "context": "CUSTOMER: Return drop-off code problem.\nBRAND: Has the 30-day return drop-off window elapsed?\nCUSTOMER: The QR drop-off code generated for The UPS Store shows expired on my phone. How do I regenerate it?",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Expired return QR code renewal request.",
        "category": "RETURN_PICKUP",
    },
    {
        "customer_message": "Instead of waiting for a courier pickup at my home, would it be possible to bring this return parcel to a local counter myself?",
        "context": "CUSTOMER: Modifying return drop-off selection.\nBRAND: Would you prefer an instant QR code return at a nearby store?\nCUSTOMER: Instead of waiting for a courier pickup at my home, would it be possible to bring this return parcel to a local counter myself?",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Changing return drop-off channel.",
        "category": "RETURN_PICKUP",
    },
    {
        "customer_message": "Return courier arrived but did not have the shipping label with him as promised by Amazon returns center.",
        "context": "CUSTOMER: Courier pickup issue today.\nBRAND: Did the courier accept the package without a barcode?\nCUSTOMER: Return courier arrived but did not have the shipping label with him as promised by Amazon returns center.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Courier arrived without designated return label.",
        "category": "RETURN_PICKUP",
    },
    {
        "customer_message": "Where can I find an Amazon Locker or drop-off location near zip code 94107 that accepts returns without a box?",
        "context": "CUSTOMER: Where can I find an Amazon Locker or drop-off location near zip code 94107 that accepts returns without a box?",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Locker return locator request.",
        "category": "RETURN_PICKUP",
    },
    {
        "customer_message": "Can I combine two separate item returns into a single shipping box to save trips to the drop-off counter?",
        "context": "CUSTOMER: Can I combine two separate item returns into a single shipping box to save trips to the drop-off counter?",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Consolidated package return policy question.",
        "category": "RETURN_PICKUP",
    },

    # --- 8 Refund Status Inquiry Cases ---
    {
        "customer_message": "I have contacted support 4 times over 3 weeks for my refund after the return was confirmed received, and still no credit or explanation!",
        "context": "CUSTOMER: Missing refund on returned merchandise.\nBRAND: Have you verified the return delivery confirmation tracking?\nCUSTOMER: I have contacted support 4 times over 3 weeks for my refund after the return was confirmed received, and still no credit or explanation!",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Four unresolved support inquiries regarding missing refund credit.",
        "category": "REPEATED_SUPPORT",
    },
    {
        "customer_message": "Representative promised my refund would be processed in 48 hours, but that window passed a week ago and nobody can tell me what happened.",
        "context": "CUSTOMER: Following up on promised refund processing.\nBRAND: Did our billing specialist confirm a manual refund authorization?\nCUSTOMER: Representative promised my refund would be processed in 48 hours, but that window passed a week ago and nobody can tell me what happened.",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Broken refund timeline commitment requiring escalation.",
        "category": "REPEATED_SUPPORT",
    },
    {
        "customer_message": "Tracking confirms Amazon warehouse received my return on Tuesday. When will the refund post to my credit card?",
        "context": "CUSTOMER: Checking on return package refund.\nBRAND: Have you received confirmation of package receipt at the fulfillment center?\nCUSTOMER: Tracking confirms Amazon warehouse received my return on Tuesday. When will the refund post to my credit card?",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Standard refund post-timing question following verified return arrival.",
        "category": "REFUND_STATUS",
    },
    {
        "customer_message": "Cancelled an order before dispatch. How many business days does it take for the funds to release back to my debit card?",
        "context": "CUSTOMER: Refund timeline inquiry on cancelled order.\nBRAND: Was the cancellation completed before shipping authorization?\nCUSTOMER: Cancelled an order before dispatch. How many business days does it take for the funds to release back to my debit card?",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Pre-dispatch cancellation authorization reversal timeframe.",
        "category": "REFUND_STATUS",
    },
    {
        "customer_message": "My return was approved for Amazon gift card balance credit, where can I verify the balance in my wallet?",
        "context": "CUSTOMER: Checking gift card credit from return.\nBRAND: Did you select gift card balance as your preferred refund method?\nCUSTOMER: My return was approved for Amazon gift card balance credit, where can I verify the balance in my wallet?",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Gift card credit verification in user account.",
        "category": "REFUND_STATUS",
    },
    {
        "customer_message": "I sent my bank statement proof showing no credit received for order #113-9021844-3391022. Can you check with billing?",
        "context": "CUSTOMER: Following up on missing credit.\nBRAND: Did you verify with your banking institution whether an authorization hold exists?\nCUSTOMER: I sent my bank statement proof showing no credit received for order #113-9021844-3391022. Can you check with billing?",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "DETAILS_ALREADY_PROVIDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer supplied bank statement proof; asking agent to check billing.",
        "category": "REFUND_STATUS",
    },
    {
        "customer_message": "What is the standard refund processing timeline for payments made using an Amazon gift card?",
        "context": "CUSTOMER: What is the standard refund processing timeline for payments made using an Amazon gift card?",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Gift card refund policy inquiry.",
        "category": "REFUND_STATUS",
    },
    {
        "customer_message": "I already contacted support yesterday to inquire about refund timing, just checking if status updated today.",
        "context": "CUSTOMER: I already contacted support yesterday to inquire about refund timing, just checking if status updated today.",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Single support contact negative control; should NOT escalate.",
        "category": "SINGLE_CONTACT_CONTROL",
    },
]
