"""Security and Account Login Cases for Golden V3.

Contains 28 cases:
- 18 High-Risk Escalation cases (unauthorized takeover, credential updates without consent, fraudulent orders from compromise, lockouts with failed recovery)
- 10 Normal Auto-Handle cases (routine password reset, OTP questions, MFA configuration, voluntary credential updates)
"""

SECURITY_AND_LOGIN_CASES = [
    # --- 18 High-Risk Security Compromise & Lockout Cases ---
    {
        "customer_message": "Someone infiltrated my Amazon profile and charged hundreds of dollars in digital gift cards! I need this stopped immediately!",
        "context": "CUSTOMER: Someone infiltrated my Amazon profile and charged hundreds of dollars in digital gift cards! I need this stopped immediately!",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Unauthorized account takeover with fraudulent gift card charges.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "Got a notification that my primary login email was switched to a yopmail address. I never authorized this! Please help recover my account.",
        "context": "CUSTOMER: Received a critical security notification on my smartphone.\nBRAND: Did the alert specify any unauthorized changes to your credentials?\nCUSTOMER: Got a notification that my primary login email was switched to a yopmail address. I never authorized this! Please help recover my account.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Unauthorized email change reported by customer.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "My account was hijacked while I was on vacation and multiple orders were dispatched to a locker in Miami that isn't mine.",
        "context": "CUSTOMER: Need urgent investigation on unexpected delivery dispatch emails.\nBRAND: Can you check if those orders reflect on your recent order history?\nCUSTOMER: My account was hijacked while I was on vacation and multiple orders were dispatched to a locker in Miami that isn't mine.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Account hijacked with fraudulent orders to unfamiliar location.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "I suspect someone else accessed my account because items are appearing in my browsing and purchase history that I never searched for or ordered.",
        "context": "CUSTOMER: I'm noticing very strange things in my Amazon profile.\nBRAND: Could you describe what unusual activity you are seeing?\nCUSTOMER: I suspect someone else accessed my account because items are appearing in my browsing and purchase history that I never searched for or ordered.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Unrecognized purchase history indicating unauthorized access.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "I never requested that password change notification I got at 3 AM. Now I'm locked out and terrified someone stole my payment cards.",
        "context": "CUSTOMER: Something is wrong, my account password stopped working overnight.\nBRAND: Did you receive any security emails regarding your credentials?\nCUSTOMER: I never requested that password change notification I got at 3 AM. Now I'm locked out and terrified someone stole my payment cards.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Unsolicited password change with lockout and fraud risk.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "There are unauthorized transactions showing on my account from yesterday that weren't me. Someone has breached my login.",
        "context": "CUSTOMER: Fraud alert on my registered debit card from Amazon.\nBRAND: Have you verified the purchase history under Your Orders?\nCUSTOMER: There are unauthorized transactions showing on my account from yesterday that weren't me. Someone has breached my login.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Account breach resulting in unauthorized transactions.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "Someone broke into my Amazon account and added an unknown phone number for two-step verification so I can't receive the OTP!",
        "context": "CUSTOMER: I am unable to receive my login verification code.\nBRAND: Is your primary phone number showing on the 2FA prompt?\nCUSTOMER: Someone broke into my Amazon account and added an unknown phone number for two-step verification so I can't receive the OTP!",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Intruder compromised account by adding unauthorized 2FA device.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "An intruder took over my account and placed an order for high-end gaming equipment to an address I've never heard of.",
        "context": "CUSTOMER: Urgent help needed with an order placed without my consent.\nBRAND: What specific details can you provide about the order?\nCUSTOMER: An intruder took over my account and placed an order for high-end gaming equipment to an address I've never heard of.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Account takeover with unauthorized order placement.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "I think my credentials were compromised in a data leak. Someone is currently logged into my account changing my shipping addresses.",
        "context": "CUSTOMER: Seeing address changes in my account settings right now.\nBRAND: Did you recently update any shipping preferences?\nCUSTOMER: I think my credentials were compromised in a data leak. Someone is currently logged into my account changing my shipping addresses.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Active unauthorized account manipulation following credential compromise.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "My Amazon account has been taken over by a scammer who changed my recovery credentials without my consent.",
        "context": "CUSTOMER: Emergency: account locked out and recovery options altered.\nBRAND: Have you tried resetting via your original recovery email?\nCUSTOMER: My Amazon account has been taken over by a scammer who changed my recovery credentials without my consent.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Malicious account takeover with altered recovery credentials.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "Received an alert saying my password and security phone were updated. It was not me! Please freeze the account before they buy anything.",
        "context": "CUSTOMER: Security alert received 5 minutes ago.\nBRAND: Did you initiate a credential update recently?\nCUSTOMER: Received an alert saying my password and security phone were updated. It was not me! Please freeze the account before they buy anything.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Unauthorized credential alteration requiring immediate specialist lock.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "Somebody hacked into my account and bought a luxury watch using my saved Amazon store card!",
        "context": "CUSTOMER: Fraud alert on my Amazon store card.\nBRAND: Did you authorize this purchase on your account?\nCUSTOMER: Somebody hacked into my account and bought a luxury watch using my saved Amazon store card!",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Compromised account used for high-value unauthorized store card purchase.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "My account was compromised, the hacker changed the email address, and customer service locked the profile, but I haven't received recovery instructions.",
        "context": "CUSTOMER: Following up on security ticket #SEC-882194.\nBRAND: Did you check your secondary email inbox for the verification link?\nCUSTOMER: My account was compromised, the hacker changed the email address, and customer service locked the profile, but I haven't received recovery instructions.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Compromised profile locked without follow-up recovery guidance.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "I never made any request to change my password or phone, but both were updated 20 minutes ago and now my sign-in fails.",
        "context": "CUSTOMER: Suddenly logged out while browsing on the shopping app.\nBRAND: What message appears when you re-enter your credentials?\nCUSTOMER: I never made any request to change my password or phone, but both were updated 20 minutes ago and now my sign-in fails.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Unsolicited password and phone changes causing lockout.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "My account is on hold due to suspicious activity. I submitted my utility bill and government ID three times but verification keeps failing and I can't sign in.",
        "context": "CUSTOMER: My account is on hold due to suspicious activity. I submitted my utility bill and government ID three times but verification keeps failing and I can't sign in.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "DETAILS_ALREADY_PROVIDED",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Suspicious account hold with repeated failed document verification.",
        "category": "ACCOUNT_LOCK_FAILED_RECOVERY",
    },
    {
        "customer_message": "Account was locked after placing an order. Password reset says successful but throws an immediate login error every single time I attempt to enter.",
        "context": "CUSTOMER: My account was put on hold after ordering computer parts.\nBRAND: Have you attempted the self-service password reset?\nCUSTOMER: Account was locked after placing an order. Password reset says successful but throws an immediate login error every single time I attempt to enter.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Locked account caught in broken password reset loop.",
        "category": "ACCOUNT_LOCK_FAILED_RECOVERY",
    },
    {
        "customer_message": "Account has been suspended for address verification. Sent the requested bank statement a week ago and still can't log in despite waiting.",
        "context": "CUSTOMER: Account suspended pending document verification.\nBRAND: Have you uploaded the utility bill or bank statement via the secure portal?\nCUSTOMER: Account has been suspended for address verification. Sent the requested bank statement a week ago and still can't log in despite waiting.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Suspended account pending unfulfilled document review beyond timeline.",
        "category": "ACCOUNT_LOCK_FAILED_RECOVERY",
    },
    {
        "customer_message": "Amazon locked my account due to unusual activity and every time I follow the recovery link it loops back to the locked screen without letting me upload proof.",
        "context": "CUSTOMER: Trying to recover my account after receiving a security lock.\nBRAND: Did the link in your email prompt you for documentation?\nCUSTOMER: Amazon locked my account due to unusual activity and every time I follow the recovery link it loops back to the locked screen without letting me upload proof.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Recovery link defect preventing verification on locked account.",
        "category": "ACCOUNT_LOCK_FAILED_RECOVERY",
    },

    # --- 10 Normal Auto-Handle Cases (Negative Controls) ---
    {
        "customer_message": "I forgot my password and need the link to reset it.",
        "context": "CUSTOMER: I forgot my password and need the link to reset it.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Routine password reset request without compromise.",
        "category": "ROUTINE_LOGIN",
    },
    {
        "customer_message": "Can you guide me on how to set up the Amazon Authenticator app on my new smartphone?",
        "context": "CUSTOMER: Can you guide me on how to set up the Amazon Authenticator app on my new smartphone?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Routine two-factor authentication setup assistance.",
        "category": "ROUTINE_LOGIN",
    },
    {
        "customer_message": "I lost my old phone and need to update my 2-step verification phone number to receive OTP codes.",
        "context": "CUSTOMER: Need to adjust security verification settings.\nBRAND: Are you currently able to access your primary email account?\nCUSTOMER: I lost my old phone and need to update my 2-step verification phone number to receive OTP codes.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Normal update of 2FA phone number after device change.",
        "category": "ROUTINE_LOGIN",
    },
    {
        "customer_message": "Having trouble signing in because my password manager filled an old password. Where is login assistance?",
        "context": "CUSTOMER: Trouble accessing my account this morning.\nBRAND: Are you receiving an incorrect password prompt?\nCUSTOMER: Having trouble signing in because my password manager filled an old password. Where is login assistance?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Standard login assistance query.",
        "category": "ROUTINE_LOGIN",
    },
    {
        "customer_message": "How do I switch the primary email address on my Amazon account to my new work email?",
        "context": "CUSTOMER: Account settings question.\nBRAND: Are you currently logged into your Amazon profile?\nCUSTOMER: How do I switch the primary email address on my Amazon account to my new work email?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Voluntary email update procedure.",
        "category": "ROUTINE_LOGIN",
    },
    {
        "customer_message": "I'm not receiving the one-time password code on my mobile number, can you resend it to my email?",
        "context": "CUSTOMER: Trying to sign in to purchase school supplies.\nBRAND: Did you check your SMS inbox or spam filters for the OTP code?\nCUSTOMER: I'm not receiving the one-time password code on my mobile number, can you resend it to my email?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Standard OTP delivery troubleshooting.",
        "category": "ROUTINE_LOGIN",
    },
    {
        "customer_message": "Where do I go in settings to change my account password as a routine security measure?",
        "context": "CUSTOMER: Where do I go in settings to change my account password as a routine security measure?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Routine password change settings inquiry.",
        "category": "ROUTINE_LOGIN",
    },
    {
        "customer_message": "I want to enable biometric fingerprint login on the Amazon shopping app on my Android tablet.",
        "context": "CUSTOMER: I want to enable biometric fingerprint login on the Amazon shopping app on my Android tablet.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Biometric authentication setup guidance.",
        "category": "ROUTINE_LOGIN",
    },
    {
        "customer_message": "My account says password expired and asks me to create a new one. What are the password length and character requirements?",
        "context": "CUSTOMER: My account says password expired and asks me to create a new one. What are the password length and character requirements?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Password complexity requirements question.",
        "category": "ROUTINE_LOGIN",
    },
    {
        "customer_message": "How do I sign out of all active devices from my Amazon account after using a hotel business center computer?",
        "context": "CUSTOMER: How do I sign out of all active devices from my Amazon account after using a hotel business center computer?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Routine device sign-out procedure.",
        "category": "ROUTINE_LOGIN",
    },
]
