"""Ambiguous and Out-of-Scope Cases for Golden V2.

Contains 35 cases:
- 25 AMBIGUOUS cases (greetings, vague help requests, emotional venting without issue, incomplete references)
- 10 OUT_OF_SCOPE cases (non-retail requests, coding, weather, stock prices, medical, travel, DIY hardware repair)
Includes 5 multi-turn dialogues demonstrating conversational ambiguity and out-of-scope follow-ups.
"""

AMBIGUOUS_AND_OOS_CASES = [
    # --- 25 AMBIGUOUS Cases ---
    {
        "customer_message": "Hello, good afternoon. Is someone available to help me?",
        "context": "CUSTOMER: Hello, good afternoon. Is someone available to help me?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Pure polite conversational opening without actionable problem.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "help",
        "context": "CUSTOMER: help",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Single-word ambiguous request for help.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "I need assistance with something that happened yesterday on my account.",
        "context": "CUSTOMER: I need assistance with something that happened yesterday on my account.",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Vague inquiry lacking specific problem description.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "What now?",
        "context": "CUSTOMER: Can someone help me please?\nBRAND: We are here to help! Could you share what order or account issue you are facing?\nCUSTOMER: What now?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Incomplete query with zero actionable details in multi-turn context.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "This isn't working at all.",
        "context": "CUSTOMER: Trying to use the service.\nBRAND: What feature or order are you trying to manage?\nCUSTOMER: This isn't working at all.",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Ambiguous complaint without product or service reference in multi-turn dialogue.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Can someone help me please?",
        "context": "CUSTOMER: Can someone help me please?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "General plea for assistance without support details.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Terrible customer service. Completely unacceptable experience.",
        "context": "CUSTOMER: Terrible customer service. Completely unacceptable experience.",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Emotional venting without operational support issue.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Please check your DM, I sent important information there.",
        "context": "CUSTOMER: Please check your DM, I sent important information there.",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Pointer to external private message without stated problem.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Did you get my message?",
        "context": "CUSTOMER: Did you get my message?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Ambiguous verification query.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "I have a question about my purchase.",
        "context": "CUSTOMER: I have a question about my purchase.",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Vague purchase inquiry with no item, problem, or order specified.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Why is this happening to me again???",
        "context": "CUSTOMER: Why is this happening to me again???",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Emotional distress expression without identifying the underlying event.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Hello? Is anyone there?",
        "context": "CUSTOMER: Hello? Is anyone there?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Presence check greeting.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Can you give me the link?",
        "context": "CUSTOMER: Can you give me the link?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Ambiguous reference to unspecified link.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Never mind, I will figure it out myself.",
        "context": "CUSTOMER: Never mind, I will figure it out myself.",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Conversational withdrawal without previous issue context.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Where is the button?",
        "context": "CUSTOMER: Where is the button?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Decontextualized UI query without screen or goal stated.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "This is ridiculous. Fix it.",
        "context": "CUSTOMER: This is ridiculous. Fix it.",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Imperative demand without describing the defect or issue.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Can you check something for me?",
        "context": "CUSTOMER: Can you check something for me?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Inquiry opening without specifying subject.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "I saw a notification on my phone earlier.",
        "context": "CUSTOMER: I saw a notification on my phone earlier.",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Vague notification mention lacking content or app context.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Something went wrong during checkout, but I don't know what.",
        "context": "CUSTOMER: Something went wrong during checkout, but I don't know what.",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Ambiguous error encounter with no error code, cart, or payment details.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Everything is a complete mess.",
        "context": "CUSTOMER: I'm really upset right now.\nBRAND: I am sorry to hear that. What issue are you experiencing with your account or order?\nCUSTOMER: Everything is a complete mess.",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Emotional frustration without operational details in multi-turn context.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "What does that mean?",
        "context": "CUSTOMER: What does that mean?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Unanchored clarification query.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Who am I speaking with?",
        "context": "CUSTOMER: Who am I speaking with?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Identity question without support topic.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "How long will this take?",
        "context": "CUSTOMER: How long will this take?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Duration inquiry for unspecified process.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "Is there a representative available?",
        "context": "CUSTOMER: Is there a representative available?",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Agent availability inquiry without presenting problem.",
        "category": "AMBIGUOUS",
    },
    {
        "customer_message": "I received an alert.",
        "context": "CUSTOMER: I received an alert.",
        "status": "AMBIGUOUS",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Broad statement lacking alert description or source.",
        "category": "AMBIGUOUS",
    },

    # --- 10 OUT_OF_SCOPE Cases ---
    {
        "customer_message": "Can you write a Python script using pandas to scrape real estate listings from Zillow?",
        "context": "CUSTOMER: Hello, I have a technical question.\nBRAND: Hello! What can we help you with today?\nCUSTOMER: Can you write a Python script using pandas to scrape real estate listings from Zillow?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Software engineering coding task unrelated to retail support.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "What is the weather forecast for Chicago this weekend?",
        "context": "CUSTOMER: What is the weather forecast for Chicago this weekend?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Meteorological weather query.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "What is the current stock price of Apple on NASDAQ?",
        "context": "CUSTOMER: Quick question.\nBRAND: How can we assist you?\nCUSTOMER: What is the current stock price of Apple on NASDAQ?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Financial markets investment query.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "How do I file corporate VAT tax returns for my third-party Seller Central business in the United Kingdom?",
        "context": "CUSTOMER: How do I file corporate VAT tax returns for my third-party Seller Central business in the United Kingdom?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Seller Central merchant legal/tax compliance inquiry outside retail buyer scope.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "Can you diagnose why I have a rash on my arm and recommend which antibiotic ointment I should take?",
        "context": "CUSTOMER: Can you diagnose why I have a rash on my arm and recommend which antibiotic ointment I should take?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Medical clinical diagnosis and treatment inquiry.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "What are the best tourist attractions and budget hotels to visit in Rome during September?",
        "context": "CUSTOMER: What are the best tourist attractions and budget hotels to visit in Rome during September?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Travel tourism planning advisory.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "How do I replace the timing belt and water pump on a 2014 Honda Civic engine?",
        "context": "CUSTOMER: How do I replace the timing belt and water pump on a 2014 Honda Civic engine?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Automotive mechanical repair tutorial inquiry.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "Who won the FIFA World Cup in 1998 and who scored the winning goals in the final?",
        "context": "CUSTOMER: Who won the FIFA World Cup in 1998 and who scored the winning goals in the final?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Sports trivia general knowledge question.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "Can you give me an authentic recipe for homemade Italian potato gnocchi with sage butter sauce?",
        "context": "CUSTOMER: Can you give me an authentic recipe for homemade Italian potato gnocchi with sage butter sauce?",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Culinary cooking recipe request.",
        "category": "OUT_OF_SCOPE",
    },
    {
        "customer_message": "Help me draft a formal legal lease agreement contract for renting an apartment to a commercial tenant.",
        "context": "CUSTOMER: Help me draft a formal legal lease agreement contract for renting an apartment to a commercial tenant.",
        "status": "OUT_OF_SCOPE",
        "areas": None,
        "intents": None,
        "primary_intent": None,
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Real estate legal contract drafting outside retail customer service.",
        "category": "OUT_OF_SCOPE",
    },
]
