"""Delivery and Tracking Cases for Golden V2.

Contains 52 cases across DELIVERY_AND_FULFILLMENT:
- WHERE_IS_MY_ORDER: 12 cases (including tracking number edge cases and conversational state)
- DELIVERY_DELAYED: 16 cases (including CARRIER_ALREADY_CONTACTED, WAITING_WINDOW_EXCEEDED, REPEATED_FAILED_SUPPORT_ATTEMPTS)
- MARKED_DELIVERED_NOT_RECEIVED: 14 cases (including TRACKING_ALREADY_CHECKED, multi-turn follow-ups)
- CARRIER_FEEDBACK_AND_INSTRUCTIONS: 10 cases (6 driver misconduct/refusal escalations + 4 routine instructions auto-handle)
Includes 26 rich multi-turn dialogues.
"""

DELIVERY_AND_TRACKING_CASES = [
    # --- WHERE_IS_MY_ORDER (12 cases) ---
    {
        "customer_message": "Where can I find my tracking number? I want to see which courier is handling it.",
        "context": "CUSTOMER: Where can I find my tracking number? I want to see which courier is handling it.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Asking where to locate tracking number; MUST NOT be inferred as TRACKING_ALREADY_CHECKED.",
        "category": "TRACKING_EDGE_CASES",
    },
    {
        "customer_message": "How do I find the tracking link on my order confirmation email?",
        "context": "CUSTOMER: How do I find the tracking link on my order confirmation email?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Locating tracking link guidance.",
        "category": "TRACKING_EDGE_CASES",
    },
    {
        "customer_message": "Can you check the dispatch progress of my new coffee maker? Order placed yesterday.",
        "context": "CUSTOMER: Can you check the dispatch progress of my new coffee maker? Order placed yesterday.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Routine package whereabouts inquiry within initial delivery timeframe.",
        "category": "ROUTINE_DELIVERY",
    },
    {
        "customer_message": "What is the estimated delivery date for my textbook package to Miami?",
        "context": "CUSTOMER: What is the estimated delivery date for my textbook package to Miami?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Standard ETA query.",
        "category": "ROUTINE_DELIVERY",
    },
    {
        "customer_message": "I already checked the tracking, what does this mean when it says departed sorting hub?",
        "context": "CUSTOMER: Can you check on order 112-9901823-1120938?\nBRAND: We are checking shipping status. Have you reviewed the carrier tracking portal?\nCUSTOMER: I already checked the tracking, what does this mean when it says departed sorting hub?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer explicitly checked tracking status and requests status meaning interpretation.",
        "category": "TRACKING_EDGE_CASES",
    },
    {
        "customer_message": "Is there a way to track the Amazon delivery van in real-time on a live map?",
        "context": "CUSTOMER: Is there a way to track the Amazon delivery van in real-time on a live map?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Map tracking feature inquiry.",
        "category": "ROUTINE_DELIVERY",
    },
    {
        "customer_message": "I provided the order number 114-8890213-9912401 in my initial chat, any news on shipping?",
        "context": "CUSTOMER: Hello, I have an inquiry about order 114-8890213-9912401.\nBRAND: Thanks for contacting us. Could you share what item or details you are inquiring about?\nCUSTOMER: I provided the order number 114-8890213-9912401 in my initial chat, any news on shipping?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "DETAILS_ALREADY_PROVIDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Multi-turn context where order number was already supplied.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "I checked the status but where do I find the tracking number?",
        "context": "CUSTOMER: I was looking at my order details online.\nBRAND: Were you able to see the fulfillment status for your items?\nCUSTOMER: I checked the status but where do I find the tracking number?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer inspected status portal but seeks exact tracking number.",
        "category": "TRACKING_EDGE_CASES",
    },
    {
        "customer_message": "Which shipping carrier is bringing my package today, USPS or Amazon logistics?",
        "context": "CUSTOMER: Which shipping carrier is bringing my package today, USPS or Amazon logistics?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Carrier identification query.",
        "category": "ROUTINE_DELIVERY",
    },
    {
        "customer_message": "I already gave you my tracking number and order details in the previous message, when will it arrive at my local depot?",
        "context": "CUSTOMER: Checking shipment for order 109-2231904-4412903 tracking TBA99281203.\nBRAND: Thanks, we see your package is in transit.\nCUSTOMER: I already gave you my tracking number and order details in the previous message, when will it arrive at my local depot?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "DETAILS_ALREADY_PROVIDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Multi-turn where tracking details were already provided in prior turn.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "Tracking page indicates 'Package arrived at carrier facility', how long until out for delivery?",
        "context": "CUSTOMER: My package is shipping from the Reno fulfillment center.\nBRAND: Have you checked the carrier tracking updates today?\nCUSTOMER: Tracking page indicates 'Package arrived at carrier facility', how long until out for delivery?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Interpretation of tracking status updates.",
        "category": "TRACKING_EDGE_CASES",
    },
    {
        "customer_message": "I need to know what time of day Amazon drivers normally deliver to residential areas.",
        "context": "CUSTOMER: I need to know what time of day Amazon drivers normally deliver to residential areas.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "WHERE_IS_MY_ORDER",
        "primary_intent": "WHERE_IS_MY_ORDER",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Delivery window general information.",
        "category": "ROUTINE_DELIVERY",
    },

    # --- DELIVERY_DELAYED (16 cases) ---
    {
        "customer_message": "My Prime delivery was guaranteed for yesterday by 8pm but never showed up. Where is it?",
        "context": "CUSTOMER: My Prime delivery was guaranteed for yesterday by 8pm but never showed up. Where is it?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Standard delayed delivery inquiry.",
        "category": "ROUTINE_DELIVERY",
    },
    {
        "customer_message": "Package was supposed to arrive 3 days ago. Tracking says delayed in transit due to weather.",
        "context": "CUSTOMER: Checking on my delayed gaming console.\nBRAND: Have you seen any updates on the carrier tracking page?\nCUSTOMER: Package was supposed to arrive 3 days ago. Tracking says delayed in transit due to weather.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer checked tracking and saw confirmed delay notice.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "I contacted UPS already and they told me Amazon hasn't handed over the parcel yet.",
        "context": "CUSTOMER: My package 112-9901823-1120938 was delayed.\nBRAND: Have you contacted UPS regarding the handover status?\nCUSTOMER: I contacted UPS already and they told me Amazon hasn't handed over the parcel yet.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "CARRIER_ALREADY_CONTACTED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer already contacted courier UPS directly.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "Called FedEx this morning and the driver said the shipment was rescheduled for next week.",
        "context": "CUSTOMER: Package was scheduled for Tuesday delivery.\nBRAND: Did FedEx provide any updated ETA for delivery?\nCUSTOMER: Called FedEx this morning and the driver said the shipment was rescheduled for next week.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "CARRIER_ALREADY_CONTACTED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Carrier contacted by customer regarding rescheduling.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "The support rep told me on Monday to wait 48 hours. It is now Friday and still no parcel!",
        "context": "CUSTOMER: Following up on ticket regarding late order.\nBRAND: What timeframe did our representative previously advise you to wait?\nCUSTOMER: The support rep told me on Monday to wait 48 hours. It is now Friday and still no parcel!",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Waiting window advised by support elapsed without delivery.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "I already contacted support twice about this delayed package. This is my third attempt and still no help.",
        "context": "CUSTOMER: Need an update on order 113-8829102-4491029.\nBRAND: Can you share details about your recent contacts with us regarding this order?\nCUSTOMER: I already contacted support twice about this delayed package. This is my third attempt and still no help.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Repeated customer support contacts regarding chronic delay.",
        "category": "REPEATED_FAILED_SUPPORT",
    },
    {
        "customer_message": "My birthday gift order is 4 days overdue and tracking has had no movement since Tuesday.",
        "context": "CUSTOMER: My birthday gift order is 4 days overdue and tracking has had no movement since Tuesday.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Stalled tracking status checked by customer.",
        "category": "TRACKING_EDGE_CASES",
    },
    {
        "customer_message": "I already gave you my tracking number and order details in the previous message. When is it arriving?",
        "context": "CUSTOMER: Order 111-2093841-0029381 tracking TBA99182312.\nBRAND: Thanks, we'd like to check this for you. Could you share your order number again?\nCUSTOMER: I already gave you my tracking number and order details in the previous message. When is it arriving?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "DETAILS_ALREADY_PROVIDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer explicitly referencing already-provided order credentials in multi-turn dialogue.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "Guaranteed same-day delivery failed. It's midnight and my medicine order did not arrive.",
        "context": "CUSTOMER: Guaranteed same-day delivery failed. It's midnight and my medicine order did not arrive.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Missed same-day fulfillment window.",
        "category": "ROUTINE_DELIVERY",
    },
    {
        "customer_message": "Tracking states 'Package delayed in transit - delivery appointment scheduled'. What does appointment mean?",
        "context": "CUSTOMER: My shipment status changed today.\nBRAND: What does the tracking timeline indicate on your carrier website?\nCUSTOMER: Tracking states 'Package delayed in transit - delivery appointment scheduled'. What does appointment mean?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Inquiry regarding specialized heavy freight delivery status.",
        "category": "TRACKING_EDGE_CASES",
    },
    {
        "customer_message": "I spoke to the driver on the phone earlier and he said he ran out of time on his route.",
        "context": "CUSTOMER: My parcel did not arrive on the truck today.\nBRAND: Did the carrier reach out to you directly?\nCUSTOMER: I spoke to the driver on the phone earlier and he said he ran out of time on his route.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "CARRIER_ALREADY_CONTACTED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer contacted delivery driver directly.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "Why is my package stuck at the local distribution hub for over 48 hours?",
        "context": "CUSTOMER: Why is my package stuck at the local distribution hub for over 48 hours?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Stalled parcel at distribution center.",
        "category": "ROUTINE_DELIVERY",
    },
    {
        "customer_message": "I contacted customer care 4 times over the last two days. Still getting the runaround regarding my late order!",
        "context": "CUSTOMER: Please connect me to a supervisor right now.\nBRAND: We are here to help, what is the issue with your shipment?\nCUSTOMER: I contacted customer care 4 times over the last two days. Still getting the runaround regarding my late order!",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Repeated failed support encounters with chronic delay.",
        "category": "REPEATED_FAILED_SUPPORT",
    },
    {
        "customer_message": "Courier tracking shows delivery was attempted, but I was home all day and nobody buzzed.",
        "context": "CUSTOMER: Delivery attempted notice received.\nBRAND: Were you at home during the scheduled time window?\nCUSTOMER: Courier tracking shows delivery was attempted, but I was home all day and nobody buzzed.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "False delivery attempt recorded on tracking.",
        "category": "TRACKING_EDGE_CASES",
    },
    {
        "customer_message": "I already reported this late order yesterday. The agent promised a callback within 24 hours that never came.",
        "context": "CUSTOMER: Still waiting on callback for my shipment.\nBRAND: When was the callback scheduled for?\nCUSTOMER: I already reported this late order yesterday. The agent promised a callback within 24 hours that never came.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Broken callback commitment on delayed shipment.",
        "category": "REPEATED_FAILED_SUPPORT",
    },
    {
        "customer_message": "I have contacted support 5 separate times about this delayed parcel and each representative transfers me to someone else!",
        "context": "CUSTOMER: What is the status of ticket #889123?\nBRAND: Let me look up your previous chats.\nCUSTOMER: I have contacted support 5 separate times about this delayed parcel and each representative transfers me to someone else!",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Five previous failed support transfers on delayed package.",
        "category": "REPEATED_FAILED_SUPPORT",
    },

    # --- MARKED_DELIVERED_NOT_RECEIVED (14 cases) ---
    {
        "customer_message": "Tracking shows handed to resident at 11:30am, but no one was home and there is no parcel.",
        "context": "CUSTOMER: Looking for my package.\nBRAND: What does the delivery confirmation state on your tracking link?\nCUSTOMER: Tracking shows handed to resident at 11:30am, but no one was home and there is no parcel.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Marked delivered to resident but customer confirms absence.",
        "category": "TRACKING_EDGE_CASES",
    },
    {
        "customer_message": "I checked with my building concierge and neighbors, nobody received the parcel that says delivered.",
        "context": "CUSTOMER: My order shows delivered but I don't have it.\nBRAND: Have you checked around your property or with neighbors/building staff?\nCUSTOMER: I checked with my building concierge and neighbors, nobody received the parcel that says delivered.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Neighbor and concierge check completed without finding parcel.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "The delivery photo shows a green front door. My house has a black front door! They delivered to wrong street!",
        "context": "CUSTOMER: Package was delivered to the wrong location.\nBRAND: Does the proof-of-delivery photo in your app match your residence?\nCUSTOMER: The delivery photo shows a green front door. My house has a black front door! They delivered to wrong street!",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Proof-of-delivery photograph shows different premises.",
        "category": "TRACKING_EDGE_CASES",
    },
    {
        "customer_message": "Got notification: 'Delivered in mailbox'. My mailbox is completely empty.",
        "context": "CUSTOMER: Got notification: 'Delivered in mailbox'. My mailbox is completely empty.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Delivery to mailbox reported but receptacle empty.",
        "category": "ROUTINE_DELIVERY",
    },
    {
        "customer_message": "I spoke to courier driver who delivers to our block, he claims he left it on porch, but porch is bare.",
        "context": "CUSTOMER: Tracking says delivered but porch is empty.\nBRAND: Have you spoken with your postal carrier or delivery driver?\nCUSTOMER: I spoke to courier driver who delivers to our block, he claims he left it on porch, but porch is bare.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "CARRIER_ALREADY_CONTACTED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Carrier contacted in person regarding missing parcel.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "Amazon app says package delivered 10 mins ago. Searched everywhere around the property, nothing here.",
        "context": "CUSTOMER: Amazon app says package delivered 10 mins ago. Searched everywhere around the property, nothing here.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Recent premature delivery scan inquiry.",
        "category": "TRACKING_EDGE_CASES",
    },
    {
        "customer_message": "I already waited the 48 hours your chat agent told me to wait after missing delivery. Still nothing.",
        "context": "CUSTOMER: Following up on missing package reported Tuesday.\nBRAND: Did customer service ask you to allow a 48-hour buffer window?\nCUSTOMER: I already waited the 48 hours your chat agent told me to wait after missing delivery. Still nothing.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Standard 48-hour buffer expired on delivered-not-received parcel.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "I checked the tracking and it says delivered to receptionist, but this is a residential house with no receptionist!",
        "context": "CUSTOMER: I checked the tracking and it says delivered.\nBRAND: What specific location does the tracking note indicate?\nCUSTOMER: I checked the tracking and it says delivered to receptionist, but this is a residential house with no receptionist!",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Mismatched delivery scan type for residential address.",
        "category": "TRACKING_EDGE_CASES",
    },
    {
        "customer_message": "I already provided the order ID in previous turn. Courier marked delivered yesterday, still not received.",
        "context": "CUSTOMER: Order number 103-9928172-1002938.\nBRAND: Thanks, checking details. Could you restate the issue?\nCUSTOMER: I already provided the order ID in previous turn. Courier marked delivered yesterday, still not received.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "DETAILS_ALREADY_PROVIDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Missing delivery follow-up with details already provided.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "Camera footage shows driver never walked up to my porch, yet package marked delivered at that exact minute.",
        "context": "CUSTOMER: Camera footage shows driver never walked up to my porch, yet package marked delivered at that exact minute.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Video doorbell evidence conflicting with delivery status.",
        "category": "ROUTINE_DELIVERY",
    },
    {
        "customer_message": "Tracking says delivered to locker, but I never received a pickup code or barcode by email or SMS.",
        "context": "CUSTOMER: I went to the hub locker.\nBRAND: Did you use the pickup code displayed on your order page?\nCUSTOMER: Tracking says delivered to locker, but I never received a pickup code or barcode by email or SMS.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Amazon Hub Locker delivery missing customer pickup code.",
        "category": "ROUTINE_DELIVERY",
    },
    {
        "customer_message": "Delivered status on app, but package is nowhere to be found. Can you resend or assist?",
        "context": "CUSTOMER: Delivered status on app, but package is nowhere to be found. Can you resend or assist?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Standard missing delivered package inquiry.",
        "category": "ROUTINE_DELIVERY",
    },
    {
        "customer_message": "Called building security and checked package room, item marked delivered is definitely missing.",
        "context": "CUSTOMER: Looking for parcel marked delivered at noon.\nBRAND: Have you checked common receiving areas in your apartment building?\nCUSTOMER: Called building security and checked package room, item marked delivered is definitely missing.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Physical verification completed by customer without locating parcel.",
        "category": "ROUTINE_DELIVERY",
    },
    {
        "customer_message": "Tracking states handed directly to customer, but I was out of town all weekend! Who took my package?",
        "context": "CUSTOMER: Tracking states handed directly to customer, but I was out of town all weekend! Who took my package?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer out of town when in-person delivery scan occurred.",
        "category": "TRACKING_EDGE_CASES",
    },

    # --- CARRIER_FEEDBACK_AND_INSTRUCTIONS (10 cases: 6 escalations + 4 auto-handle) ---
    {
        "customer_message": "The delivery driver refused to deliver to my apartment door and rudely shouted at me to come down to the street or he'll return it!",
        "context": "CUSTOMER: The delivery driver just called me from outside.\nBRAND: What did the driver communicate regarding your drop-off?\nCUSTOMER: The delivery driver refused to deliver to my apartment door and rudely shouted at me to come down to the street or he'll return it!",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "CARRIER_ALREADY_CONTACTED",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Driver refusal to deliver to address accompanied by verbal aggression.",
        "category": "CARRIER_MISCONDUCT",
    },
    {
        "customer_message": "Your authorized delivery agent refused to bring parcel to my 3rd floor flat. Demanded I walk to his van. I am disabled and cannot!",
        "context": "CUSTOMER: Your authorized delivery agent refused to bring parcel to my 3rd floor flat. Demanded I walk to his van. I am disabled and cannot!",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "CARRIER_ALREADY_CONTACTED",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Delivery refusal to disabled resident requiring human specialist intervention.",
        "category": "CARRIER_MISCONDUCT",
    },
    {
        "customer_message": "Driver drove past my house, threw the heavy box out the window onto the driveway cracking the contents, and sped off!",
        "context": "CUSTOMER: Driver drove past my house, threw the heavy box out the window onto the driveway cracking the contents, and sped off!",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Reckless driver conduct and intentional property mishandling.",
        "category": "CARRIER_MISCONDUCT",
    },
    {
        "customer_message": "Courier called me and refused to enter my gated community despite giving him the gate code. He told me to pickup from depot 20 miles away.",
        "context": "CUSTOMER: The courier refused to drop off my delivery.\nBRAND: What reason did the driver provide for not completing the drop-off?\nCUSTOMER: Courier called me and refused to enter my gated community despite giving him the gate code. He told me to pickup from depot 20 miles away.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "CARRIER_ALREADY_CONTACTED",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Courier refusal to access valid gate code and forcing depot pickup.",
        "category": "CARRIER_MISCONDUCT",
    },
    {
        "customer_message": "The delivery person was extremely aggressive, used profanity towards my elderly mother when asked to place the box inside.",
        "context": "CUSTOMER: The delivery person was extremely aggressive, used profanity towards my elderly mother when asked to place the box inside.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Hostile courier behavior and verbal abuse against customer.",
        "category": "CARRIER_MISCONDUCT",
    },
    {
        "customer_message": "This is the third time this week the delivery driver refused to drop parcels at my door and marked address inaccessible when the road is clear!",
        "context": "CUSTOMER: My packages keep getting returned without delivery.\nBRAND: Have you noticed what reason is listed on your tracking page?\nCUSTOMER: This is the third time this week the delivery driver refused to drop parcels at my door and marked address inaccessible when the road is clear!",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Repeated false inaccessibility scans and chronic delivery refusal.",
        "category": "CARRIER_MISCONDUCT",
    },
    {
        "customer_message": "Can I add delivery instructions for future packages to be left behind the large planter box on my front porch?",
        "context": "CUSTOMER: Can I add delivery instructions for future packages to be left behind the large planter box on my front porch?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Standard auto-handle delivery preference instructions.",
        "category": "ROUTINE_DELIVERY",
    },
    {
        "customer_message": "Please update my carrier delivery notes with the front gate security code #8492.",
        "context": "CUSTOMER: I want to make sure the driver can get inside my building gate tomorrow.\nBRAND: You can provide gate codes or access instructions for your delivery address.\nCUSTOMER: Please update my carrier delivery notes with the front gate security code #8492.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Routine gate code instructions for carrier; safe to auto-handle.",
        "category": "ROUTINE_DELIVERY",
    },
    {
        "customer_message": "How do I leave positive feedback for today's delivery driver? She was very polite and placed the heavy box right inside.",
        "context": "CUSTOMER: How do I leave positive feedback for today's delivery driver? She was very polite and placed the heavy box right inside.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Positive carrier feedback inquiry; safe to auto-handle.",
        "category": "ROUTINE_DELIVERY",
    },
    {
        "customer_message": "Please instruct the delivery driver to ring the doorbell twice upon delivery because my dog barks at knocks.",
        "context": "CUSTOMER: Can I specify delivery instructions for my order?\nBRAND: Yes, what instructions would you like to provide for the carrier?\nCUSTOMER: Please instruct the delivery driver to ring the doorbell twice upon delivery because my dog barks at knocks.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Routine driver doorbell preference; safe to auto-handle.",
        "category": "ROUTINE_DELIVERY",
    },
]
