"""Multi-Intent and High-Risk Challenge Cases for Golden V2.

Contains 20 cases:
- Diverse multi-label combinations across the frozen taxonomy
- Multi-turn dialogues where customer messages reference earlier context
- High-risk security, driver misconduct, and repeated-attempts challenges
"""

MULTI_INTENT_CASES = [
    {
        "customer_message": "My parcel is 4 days late and when the driver finally called he was rude and told me to collect it from the curb!",
        "context": "CUSTOMER: Following up on delivery of order 112-8829102.\nBRAND: Did the carrier reach out with delivery information?\nCUSTOMER: My parcel is 4 days late and when the driver finally called he was rude and told me to collect it from the curb!",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED|CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "CARRIER_ALREADY_CONTACTED",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Multi-intent: delivery delay combined with driver misconduct and refusal.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "The glass blender arrived completely smashed inside the box. I need a courier return pickup scheduled today.",
        "context": "CUSTOMER: The glass blender arrived completely smashed inside the box. I need a courier return pickup scheduled today.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM|RETURN_PICKUP_ISSUE",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Multi-intent: damaged item reporting and return pickup arrangement.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "I received size 6 boots instead of the jacket I ordered. I want to return this and get my money refunded back to my Visa.",
        "context": "CUSTOMER: I received size 6 boots instead of the jacket I ordered. I want to return this and get my money refunded back to my Visa.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS|REFUNDS_AND_BILLING",
        "intents": "WRONG_ITEM_RECEIVED|REFUND_STATUS_INQUIRY",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Multi-intent across two areas: wrong item received and refund inquiry.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "My card was charged $139 for Prime renewal which I never asked for, and an extra $14.99 unknown fee. Cancel Prime and refund both!",
        "context": "CUSTOMER: Reviewing monthly bank transactions.\nBRAND: What Amazon charges are appearing on your card statement?\nCUSTOMER: My card was charged $139 for Prime renewal which I never asked for, and an extra $14.99 unknown fee. Cancel Prime and refund both!",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME|REFUNDS_AND_BILLING",
        "intents": "PRIME_MEMBERSHIP_MANAGEMENT|UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "primary_intent": "PRIME_MEMBERSHIP_MANAGEMENT",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Multi-intent: Prime membership cancellation coupled with disputed duplicate charge.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "I want to cancel order #111-9988223, or if it already shipped, change the delivery address to my office.",
        "context": "CUSTOMER: I want to cancel order #111-9988223, or if it already shipped, change the delivery address to my office.",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "CANCEL_ORDER_REQUEST|MODIFY_ORDER_DETAILS",
        "primary_intent": "CANCEL_ORDER_REQUEST",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Multi-intent: conditional cancellation or address modification.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "The package is over 5 days late and no longer needed for the event. Cancel this shipment and process my refund.",
        "context": "CUSTOMER: The package is over 5 days late and no longer needed for the event. Cancel this shipment and process my refund.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT|REFUNDS_AND_BILLING",
        "intents": "DELIVERY_DELAYED|REFUND_STATUS_INQUIRY",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Multi-intent: late delivery leading to refund request.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "Tracking shows delivered 3 days ago, never got the package. I already spoke to building management. Please issue a refund.",
        "context": "CUSTOMER: My package has not arrived.\nBRAND: Did you review the carrier delivery scan on your tracking page?\nCUSTOMER: Tracking shows delivered 3 days ago, never got the package. I already spoke to building management. Please issue a refund.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT|REFUNDS_AND_BILLING",
        "intents": "MARKED_DELIVERED_NOT_RECEIVED|REFUND_STATUS_INQUIRY",
        "primary_intent": "MARKED_DELIVERED_NOT_RECEIVED",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Multi-intent: delivered not received accompanied by refund claim.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "Courier missed the return pickup window twice now, and I still haven't received the refund credit promised last week.",
        "context": "CUSTOMER: Ticket status regarding returned winter coat.\nBRAND: Has the return collection been finalized?\nCUSTOMER: Courier missed the return pickup window twice now, and I still haven't received the refund credit promised last week.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS|REFUNDS_AND_BILLING",
        "intents": "RETURN_PICKUP_ISSUE|REFUND_STATUS_INQUIRY",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Multi-intent: repeated pickup failure and delayed refund across multiple turns.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "Prime Video rented movie won't play due to an HDCP error, and I want a refund of the $5.99 rental charge.",
        "context": "CUSTOMER: Prime Video rented movie won't play due to an HDCP error, and I want a refund of the $5.99 rental charge.",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME|REFUNDS_AND_BILLING",
        "intents": "DIGITAL_CONTENT_ACCESS|REFUND_STATUS_INQUIRY",
        "primary_intent": "DIGITAL_CONTENT_ACCESS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Multi-intent: digital playback failure and refund claim.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "Someone hacked into my account and charged 3 unfamiliar items to my credit card! Freeze account and refund!",
        "context": "CUSTOMER: Someone hacked into my account and charged 3 unfamiliar items to my credit card! Freeze account and refund!",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY|REFUNDS_AND_BILLING",
        "intents": "ACCOUNT_LOGIN_ISSUES|UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Multi-intent high-risk: account security compromise with fraudulent charges.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "A scammer committed identity theft on my Amazon profile, changed my phone number, and opened an unauthorized Prime account.",
        "context": "CUSTOMER: Security breach on my account profile.\nBRAND: What profile alterations were made without your approval?\nCUSTOMER: A scammer committed identity theft on my Amazon profile, changed my phone number, and opened an unauthorized Prime account.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY|DIGITAL_SERVICES_AND_PRIME",
        "intents": "ACCOUNT_LOGIN_ISSUES|PRIME_MEMBERSHIP_MANAGEMENT",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Multi-intent high-risk: identity theft compromise combined with unauthorized Prime account.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "Account holder has passed away. As the executor, I need to close this Amazon account and cancel all recurring Prime subscriptions.",
        "context": "CUSTOMER: Account holder has passed away. As the executor, I need to close this Amazon account and cancel all recurring Prime subscriptions.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY|DIGITAL_SERVICES_AND_PRIME",
        "intents": "ACCOUNT_LOGIN_ISSUES|PRIME_MEMBERSHIP_MANAGEMENT",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "HIGH_RISK_SECURITY",
        "notes": "Multi-intent high-risk estate probate and account closure requiring verification.",
        "category": "HIGH_RISK_POLICY",
    },
    {
        "customer_message": "Package has been missing for two weeks. If you don't issue my full refund immediately, I am filing a complaint with the state attorney general and credit card bank!",
        "context": "CUSTOMER: Late delivery follow-up on order 113-9912038.\nBRAND: We are reviewing tracking with the carrier.\nCUSTOMER: Package has been missing for two weeks. If you don't issue my full refund immediately, I am filing a complaint with the state attorney general and credit card bank!",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT|REFUNDS_AND_BILLING",
        "intents": "DELIVERY_DELAYED|REFUND_STATUS_INQUIRY",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "HIGH_RISK_SECURITY",
        "notes": "Multi-intent high-risk: chronic delivery failure with formal legal escalation threat.",
        "category": "HIGH_RISK_POLICY",
    },
    {
        "customer_message": "Driver threw package over gate which broke the ceramic vase inside. I want to report this carrier and get a free replacement sent.",
        "context": "CUSTOMER: Driver threw package over gate which broke the ceramic vase inside. I want to report this carrier and get a free replacement sent.",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT|RETURNS_AND_REPLACEMENTS",
        "intents": "CARRIER_FEEDBACK_AND_INSTRUCTIONS|DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "CARRIER_FEEDBACK_AND_INSTRUCTIONS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "CARRIER_MISCONDUCT_AND_REFUSAL",
        "notes": "Multi-intent: carrier misconduct and damaged product replacement.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "I ordered an espresso machine but received a damaged electric kettle that has a dented base.",
        "context": "CUSTOMER: I ordered an espresso machine but received a damaged electric kettle that has a dented base.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED|DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Multi-intent: wrong item received that is also damaged.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "My order was split into two packages. One arrived yesterday, but where is the second package that is now delayed?",
        "context": "CUSTOMER: Checking shipment for order 114-2201938.\nBRAND: Your order was split into multiple fulfillment shipments.\nCUSTOMER: My order was split into two packages. One arrived yesterday, but where is the second package that is now delayed?",
        "status": "NORMAL",
        "areas": "DELIVERY_AND_FULFILLMENT",
        "intents": "DELIVERY_DELAYED|WHERE_IS_MY_ORDER",
        "primary_intent": "DELIVERY_DELAYED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Multi-intent: split shipment whereabouts and transit delay.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "I want to cancel the renewal on Prime and update my billing address on file for my standard retail orders.",
        "context": "CUSTOMER: Account maintenance request.\nBRAND: What profile settings would you like to adjust?\nCUSTOMER: I want to cancel the renewal on Prime and update my billing address on file for my standard retail orders.",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME|ORDER_MANAGEMENT",
        "intents": "PRIME_MEMBERSHIP_MANAGEMENT|MODIFY_ORDER_DETAILS",
        "primary_intent": "PRIME_MEMBERSHIP_MANAGEMENT",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Multi-intent: Prime membership cancellation and profile address update.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "UPS failed to pick up my return box, and the replacement order you shipped is also delayed in transit!",
        "context": "CUSTOMER: Tracking both my return and replacement order.\nBRAND: What issues are you encountering with these shipments?\nCUSTOMER: UPS failed to pick up my return box, and the replacement order you shipped is also delayed in transit!",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS|DELIVERY_AND_FULFILLMENT",
        "intents": "RETURN_PICKUP_ISSUE|DELIVERY_DELAYED",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Multi-intent: missed return pickup combined with delayed replacement order.",
        "category": "MULTI_INTENT",
    },
    {
        "customer_message": "I already called support 4 times about this unauthorized Prime renewal and duplicate billing charge. Nobody has fixed it!",
        "context": "CUSTOMER: Connecting regarding disputed fees.\nBRAND: How many prior attempts have been made to resolve this?\nCUSTOMER: I already called support 4 times about this unauthorized Prime renewal and duplicate billing charge. Nobody has fixed it!",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME|REFUNDS_AND_BILLING",
        "intents": "PRIME_MEMBERSHIP_MANAGEMENT|UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "primary_intent": "PRIME_MEMBERSHIP_MANAGEMENT",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Multi-intent high-risk: repeated failed attempts regarding Prime duplicate billing.",
        "category": "REPEATED_FAILED_SUPPORT",
    },
    {
        "customer_message": "I need instructions on where to return a defective laptop battery, and whether hazardous materials require a special label.",
        "context": "CUSTOMER: I need instructions on where to return a defective laptop battery, and whether hazardous materials require a special label.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS|REFUNDS_AND_BILLING",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM|REFUND_STATUS_INQUIRY",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Multi-intent: hazardous battery return procedure and refund eligibility.",
        "category": "MULTI_INTENT",
    },
]
