"""Orders, Prime, Digital, and Billing Dispute Cases for Golden V2.

Contains 23 cases:
- CANCEL_ORDER_REQUEST: 6 cases
- MODIFY_ORDER_DETAILS: 5 cases
- PRIME_MEMBERSHIP_MANAGEMENT: 4 cases
- DIGITAL_CONTENT_ACCESS: 4 cases
- UNRECOGNIZED_OR_DUPLICATE_CHARGE: 4 cases
Includes 10 rich multi-turn dialogues.
"""

ORDERS_PRIME_DIGITAL_CASES = [
    # --- CANCEL_ORDER_REQUEST (6 cases) ---
    {
        "customer_message": "I accidentally ordered the wrong size bike helmet 10 minutes ago, please cancel the order immediately.",
        "context": "CUSTOMER: I accidentally ordered the wrong size bike helmet 10 minutes ago, please cancel the order immediately.",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "CANCEL_ORDER_REQUEST",
        "primary_intent": "CANCEL_ORDER_REQUEST",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Immediate cancellation request prior to fulfillment.",
        "category": "ORDER_MANAGEMENT",
    },
    {
        "customer_message": "Can I cancel just one item out of my 3-item order without cancelling the whole shipment?",
        "context": "CUSTOMER: Can I cancel just one item out of my 3-item order without cancelling the whole shipment?",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "CANCEL_ORDER_REQUEST",
        "primary_intent": "CANCEL_ORDER_REQUEST",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Partial line-item order cancellation inquiry.",
        "category": "ORDER_MANAGEMENT",
    },
    {
        "customer_message": "I already clicked cancel on the app but it says cancellation requested. Is it definitely cancelled?",
        "context": "CUSTOMER: Need to check cancellation status on order 114-9912038.\nBRAND: Did you request cancellation through the website or customer service?\nCUSTOMER: I already clicked cancel on the app but it says cancellation requested. Is it definitely cancelled?",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "CANCEL_ORDER_REQUEST",
        "primary_intent": "CANCEL_ORDER_REQUEST",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Cancellation status confirmation inquiry.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "My child ordered $120 of video game currency on my account without my knowledge. Please cancel and void this!",
        "context": "CUSTOMER: My child ordered $120 of video game currency on my account without my knowledge. Please cancel and void this!",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "CANCEL_ORDER_REQUEST",
        "primary_intent": "CANCEL_ORDER_REQUEST",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Accidental unauthorized child purchase cancellation.",
        "category": "ORDER_MANAGEMENT",
    },
    {
        "customer_message": "I provided the order number 113-7721832-0012938 earlier. Please confirm if cancellation went through.",
        "context": "CUSTOMER: Need to cancel order 113-7721832-0012938.\nBRAND: Thanks, let us check if the item has entered dispatch.\nCUSTOMER: I provided the order number 113-7721832-0012938 earlier. Please confirm if cancellation went through.",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "CANCEL_ORDER_REQUEST",
        "primary_intent": "CANCEL_ORDER_REQUEST",
        "state": "DETAILS_ALREADY_PROVIDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Multi-turn cancellation status follow-up with order ID provided.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "Order has been in 'shipping now' status for 4 days, the cancel button is greyed out. How can I stop delivery?",
        "context": "CUSTOMER: Trying to cancel my shipment.\nBRAND: What status is shown next to the order in your account?\nCUSTOMER: Order has been in 'shipping now' status for 4 days, the cancel button is greyed out. How can I stop delivery?",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "CANCEL_ORDER_REQUEST",
        "primary_intent": "CANCEL_ORDER_REQUEST",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Cancellation attempt while order is in advanced dispatch lock.",
        "category": "CONVERSATIONAL_STATE",
    },

    # --- MODIFY_ORDER_DETAILS (5 cases) ---
    {
        "customer_message": "I just placed an order and realized it has my old address. Can I change the delivery address to my new home?",
        "context": "CUSTOMER: I just placed an order and realized it has my old address. Can I change the delivery address to my new home?",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "MODIFY_ORDER_DETAILS",
        "primary_intent": "MODIFY_ORDER_DETAILS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Shipping address change inquiry for pending order.",
        "category": "ORDER_MANAGEMENT",
    },
    {
        "customer_message": "How do I switch the payment method for an order that hasn't shipped yet? It still says Not Yet Dispatched.",
        "context": "CUSTOMER: Realized I charged the wrong credit card.\nBRAND: Has the order entered the dispatching stage yet?\nCUSTOMER: How do I switch the payment method for an order that hasn't shipped yet? It still says Not Yet Dispatched.",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "MODIFY_ORDER_DETAILS",
        "primary_intent": "MODIFY_ORDER_DETAILS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Changing payment card before dispatch in multi-turn conversation.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "Can I add gift wrapping and a personalized message card to my order before it ships?",
        "context": "CUSTOMER: Can I add gift wrapping and a personalized message card to my order before it ships?",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "MODIFY_ORDER_DETAILS",
        "primary_intent": "MODIFY_ORDER_DETAILS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Adding gift options post-checkout.",
        "category": "ORDER_MANAGEMENT",
    },
    {
        "customer_message": "I already gave you the correct street number 442 Elm St in my previous turn. Did the address get updated?",
        "context": "CUSTOMER: Address correction needed for order 112-8819203.\nBRAND: What is the corrected street address?\nCUSTOMER: I already gave you the correct street number 442 Elm St in my previous turn. Did the address get updated?",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "MODIFY_ORDER_DETAILS",
        "primary_intent": "MODIFY_ORDER_DETAILS",
        "state": "DETAILS_ALREADY_PROVIDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer referencing previously supplied corrected address.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "Can I upgrade my shipping speed from Standard to One-Day Delivery for an extra charge?",
        "context": "CUSTOMER: Can I upgrade my shipping speed from Standard to One-Day Delivery for an extra charge?",
        "status": "NORMAL",
        "areas": "ORDER_MANAGEMENT",
        "intents": "MODIFY_ORDER_DETAILS",
        "primary_intent": "MODIFY_ORDER_DETAILS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Shipping speed modification request.",
        "category": "ORDER_MANAGEMENT",
    },

    # --- PRIME_MEMBERSHIP_MANAGEMENT (4 cases) ---
    {
        "customer_message": "Amazon auto-renewed my annual Prime subscription yesterday. I don't use Prime anymore, can I cancel and get a full refund?",
        "context": "CUSTOMER: Billing notification received for Prime.\nBRAND: What plan or charge appeared on your statement?\nCUSTOMER: Amazon auto-renewed my annual Prime subscription yesterday. I don't use Prime anymore, can I cancel and get a full refund?",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "PRIME_MEMBERSHIP_MANAGEMENT",
        "primary_intent": "PRIME_MEMBERSHIP_MANAGEMENT",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Prime annual renewal cancellation and refund request.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "How do I cancel my 30-day Prime free trial before it charges my credit card next Tuesday?",
        "context": "CUSTOMER: How do I cancel my 30-day Prime free trial before it charges my credit card next Tuesday?",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "PRIME_MEMBERSHIP_MANAGEMENT",
        "primary_intent": "PRIME_MEMBERSHIP_MANAGEMENT",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Free trial cancellation before auto-conversion.",
        "category": "PRIME_MANAGEMENT",
    },
    {
        "customer_message": "How can I share my Amazon Prime delivery benefits with my spouse through Amazon Household?",
        "context": "CUSTOMER: How can I share my Amazon Prime delivery benefits with my spouse through Amazon Household?",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "PRIME_MEMBERSHIP_MANAGEMENT",
        "primary_intent": "PRIME_MEMBERSHIP_MANAGEMENT",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Amazon Household benefit sharing setup.",
        "category": "PRIME_MANAGEMENT",
    },
    {
        "customer_message": "I was charged twice for Prime membership this month on the 3rd and the 15th. Please refund the duplicate fee.",
        "context": "CUSTOMER: Disputing multiple Prime membership fees.\nBRAND: Can you verify the charge amounts and dates from your card?\nCUSTOMER: I was charged twice for Prime membership this month on the 3rd and the 15th. Please refund the duplicate fee.",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "PRIME_MEMBERSHIP_MANAGEMENT",
        "primary_intent": "PRIME_MEMBERSHIP_MANAGEMENT",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Duplicate monthly Prime membership billing inquiry.",
        "category": "CONVERSATIONAL_STATE",
    },

    # --- DIGITAL_CONTENT_ACCESS (4 cases) ---
    {
        "customer_message": "Purchased a Kindle ebook 2 hours ago but it is not syncing to my Paperwhite device.",
        "context": "CUSTOMER: Purchased a Kindle ebook 2 hours ago but it is not syncing to my Paperwhite device.",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "DIGITAL_CONTENT_ACCESS",
        "primary_intent": "DIGITAL_CONTENT_ACCESS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Kindle ebook sync troubleshooting.",
        "category": "DIGITAL_SERVICES",
    },
    {
        "customer_message": "Prime Video app keeps giving error code 5004 on my Samsung smart TV whenever I try to play the movie.",
        "context": "CUSTOMER: Cannot stream my video purchase.\nBRAND: What happens when you try to launch the title?\nCUSTOMER: Prime Video app keeps giving error code 5004 on my Samsung smart TV whenever I try to play the movie.",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "DIGITAL_CONTENT_ACCESS",
        "primary_intent": "DIGITAL_CONTENT_ACCESS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Prime Video streaming DRM playback error code.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "Rented a movie on Amazon Video but the audio is out of sync with video by 3 seconds.",
        "context": "CUSTOMER: Rented a movie on Amazon Video but the audio is out of sync with video by 3 seconds.",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "DIGITAL_CONTENT_ACCESS",
        "primary_intent": "DIGITAL_CONTENT_ACCESS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Digital rental playback quality defect.",
        "category": "DIGITAL_SERVICES",
    },
    {
        "customer_message": "My Audible audiobook purchase won't play on my smartphone app, says license expired.",
        "context": "CUSTOMER: My Audible audiobook purchase won't play on my smartphone app, says license expired.",
        "status": "NORMAL",
        "areas": "DIGITAL_SERVICES_AND_PRIME",
        "intents": "DIGITAL_CONTENT_ACCESS",
        "primary_intent": "DIGITAL_CONTENT_ACCESS",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Audible digital licensing verification issue.",
        "category": "DIGITAL_SERVICES",
    },

    # --- UNRECOGNIZED_OR_DUPLICATE_CHARGE (4 cases) ---
    {
        "customer_message": "There is an unknown charge of $29.99 on my credit card bill from AMZN Digital that I don't recognize.",
        "context": "CUSTOMER: There is an unknown charge of $29.99 on my credit card bill from AMZN Digital that I don't recognize.",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "primary_intent": "UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Unrecognized digital charge investigation inquiry.",
        "category": "BILLING_DISPUTES",
    },
    {
        "customer_message": "My bank statement shows two identical charges of $49.50 for the exact same order placed on Thursday. Void the extra one.",
        "context": "CUSTOMER: Billing discrepancy on my credit card.\nBRAND: What transaction details are showing on your statement?\nCUSTOMER: My bank statement shows two identical charges of $49.50 for the exact same order placed on Thursday. Void the extra one.",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "primary_intent": "UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Duplicate billing transaction on single checkout.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "I have not made any Amazon purchases in 6 months, why did I get billed $14.99 yesterday?",
        "context": "CUSTOMER: I have not made any Amazon purchases in 6 months, why did I get billed $14.99 yesterday?",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "primary_intent": "UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Inactive account subscription charge inquiry.",
        "category": "BILLING_DISPUTES",
    },
    {
        "customer_message": "I already gave you the transaction ID and card last 4 digits in my first message. Can you check this unknown charge?",
        "context": "CUSTOMER: Unknown charge of $19.99 on card ending in 4102, transaction ID TX-889102.\nBRAND: Thanks, we are checking billing records.\nCUSTOMER: I already gave you the transaction ID and card last 4 digits in my first message. Can you check this unknown charge?",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "primary_intent": "UNRECOGNIZED_OR_DUPLICATE_CHARGE",
        "state": "DETAILS_ALREADY_PROVIDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer referencing previously supplied transaction credentials.",
        "category": "CONVERSATIONAL_STATE",
    },
]
