"""Returns, Replacements, and Refunds Cases for Golden V2.

Contains 42 cases across RETURNS_AND_REPLACEMENTS and REFUNDS_AND_BILLING:
- DAMAGED_OR_DEFECTIVE_ITEM: 10 cases
- WRONG_ITEM_RECEIVED: 10 cases
- RETURN_PICKUP_ISSUE: 10 cases
- REFUND_STATUS_INQUIRY: 12 cases
Includes 21 rich multi-turn dialogues and 7 repeated-failed-support challenge cases.
"""

RETURNS_AND_REFUNDS_CASES = [
    # --- DAMAGED_OR_DEFECTIVE_ITEM (10 cases) ---
    {
        "customer_message": "The ceramic dinner set arrived shattered in pieces inside the box. Shards everywhere. How do I get a replacement?",
        "context": "CUSTOMER: The ceramic dinner set arrived shattered in pieces inside the box. Shards everywhere. How do I get a replacement?",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Severely damaged fragile item on arrival.",
        "category": "DAMAGED_ITEM",
    },
    {
        "customer_message": "Liquid laundry detergent bottle cracked open during shipping and soaked the entire carton.",
        "context": "CUSTOMER: Liquid laundry detergent bottle cracked open during shipping and soaked the entire carton.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Leaking damaged household goods in transit.",
        "category": "DAMAGED_ITEM",
    },
    {
        "customer_message": "The tablet turns on but the touchscreen has dead zones and doesn't register touches on the right side.",
        "context": "CUSTOMER: Need troubleshooting for tablet purchased last week.\nBRAND: Have you noticed any hardware or physical display issues?\nCUSTOMER: The tablet turns on but the touchscreen has dead zones and doesn't register touches on the right side.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Defective electronics screen digitizer failure.",
        "category": "DAMAGED_ITEM",
    },
    {
        "customer_message": "I already sent pictures of the smashed television screen to support yesterday. When is replacement shipping?",
        "context": "CUSTOMER: Television arrived smashed.\nBRAND: Please upload photos through the online return center.\nCUSTOMER: I already sent pictures of the smashed television screen to support yesterday. When is replacement shipping?",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "DETAILS_ALREADY_PROVIDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer already submitted damage photographic evidence.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "Brand new blender motor started smoking upon first use. Extremely dangerous defect.",
        "context": "CUSTOMER: Brand new blender motor started smoking upon first use. Extremely dangerous defect.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Defective electrical appliance safety hazard.",
        "category": "DAMAGED_ITEM",
    },
    {
        "customer_message": "The hardcover textbook arrived with the spine torn completely off the binding.",
        "context": "CUSTOMER: The hardcover textbook arrived with the spine torn completely off the binding.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Physical damage to book shipment.",
        "category": "DAMAGED_ITEM",
    },
    {
        "customer_message": "Headphones only produce audio in the left earbud. Right side is completely dead straight out of the box.",
        "context": "CUSTOMER: Headphones only produce audio in the left earbud. Right side is completely dead straight out of the box.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Defective audio equipment audio imbalance.",
        "category": "DAMAGED_ITEM",
    },
    {
        "customer_message": "I contacted support three times already about this broken mixer and every rep promises a supervisor callback that never happens!",
        "context": "CUSTOMER: Following up on replacement request #90123.\nBRAND: Could you let us know what previous assistance was provided?\nCUSTOMER: I contacted support three times already about this broken mixer and every rep promises a supervisor callback that never happens!",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Repeated failed support contacts regarding broken appliance replacement.",
        "category": "REPEATED_FAILED_SUPPORT",
    },
    {
        "customer_message": "The glass olive oil container shattered inside the package and contaminated all other items in the box.",
        "context": "CUSTOMER: The glass olive oil container shattered inside the package and contaminated all other items in the box.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Secondary damage from liquid breakage.",
        "category": "DAMAGED_ITEM",
    },
    {
        "customer_message": "Watch face has a deep diagonal scratch across the sapphire crystal right out of the sealed box.",
        "context": "CUSTOMER: Received my watch order today.\nBRAND: Did you inspect the packaging and watch upon unboxing?\nCUSTOMER: Watch face has a deep diagonal scratch across the sapphire crystal right out of the sealed box.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "DAMAGED_OR_DEFECTIVE_ITEM",
        "primary_intent": "DAMAGED_OR_DEFECTIVE_ITEM",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Cosmetic defect on luxury watch shipment.",
        "category": "DAMAGED_ITEM",
    },

    # --- WRONG_ITEM_RECEIVED (10 cases) ---
    {
        "customer_message": "I ordered a men's size 11 running shoe, but received a women's size 6 high heel instead.",
        "context": "CUSTOMER: I ordered a men's size 11 running shoe, but received a women's size 6 high heel instead.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Completely wrong footwear item delivered.",
        "category": "WRONG_ITEM",
    },
    {
        "customer_message": "Received a pack of baby diapers instead of the cordless drill I ordered!",
        "context": "CUSTOMER: There is a severe mixup with my parcel.\nBRAND: What item was inside the package when you opened it?\nCUSTOMER: Received a pack of baby diapers instead of the cordless drill I ordered!",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Total category mismatch fulfillment error.",
        "category": "WRONG_ITEM",
    },
    {
        "customer_message": "The shirt delivered is bright yellow, but my invoice clearly says navy blue.",
        "context": "CUSTOMER: The shirt delivered is bright yellow, but my invoice clearly says navy blue.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Apparel color variation error.",
        "category": "WRONG_ITEM",
    },
    {
        "customer_message": "I already gave you the barcode and photo of the wrong item in my first turn. What are the next steps?",
        "context": "CUSTOMER: Received wrong textbook ISBN 978-0134685991.\nBRAND: Thanks, checking the return guidelines.\nCUSTOMER: I already gave you the barcode and photo of the wrong item in my first turn. What are the next steps?",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "DETAILS_ALREADY_PROVIDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer referencing previously provided item barcode and evidence.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "Ordered a 128GB flash drive, box says 128GB but the drive inside is marked 32GB.",
        "context": "CUSTOMER: Ordered a 128GB flash drive, box says 128GB but the drive inside is marked 32GB.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Packaging mismatch / wrong internal capacity.",
        "category": "WRONG_ITEM",
    },
    {
        "customer_message": "I was sent a French language edition of the novel instead of the English version I purchased.",
        "context": "CUSTOMER: I was sent a French language edition of the novel instead of the English version I purchased.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Language edition fulfillment discrepancy.",
        "category": "WRONG_ITEM",
    },
    {
        "customer_message": "Ordered an organic olive oil 2-pack, only 1 bottle was in the box. Missing the second bottle.",
        "context": "CUSTOMER: Ordered an organic olive oil 2-pack, only 1 bottle was in the box. Missing the second bottle.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Partial multipack quantity discrepancy.",
        "category": "WRONG_ITEM",
    },
    {
        "customer_message": "This is the second time Amazon sent me the wrong color! I asked support specifically to check warehouse bin stock!",
        "context": "CUSTOMER: The replacement order arrived today.\nBRAND: Did the replacement item resolve the order issue?\nCUSTOMER: This is the second time Amazon sent me the wrong color! I asked support specifically to check warehouse bin stock!",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Repeated fulfillment error after previous support replacement.",
        "category": "REPEATED_FAILED_SUPPORT",
    },
    {
        "customer_message": "Received phone case for iPhone 13 Pro instead of iPhone 15 Pro Max. Dimensions do not fit.",
        "context": "CUSTOMER: Received phone case for iPhone 13 Pro instead of iPhone 15 Pro Max. Dimensions do not fit.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Hardware accessory model mismatch.",
        "category": "WRONG_ITEM",
    },
    {
        "customer_message": "The package had someone else's packing slip inside with a different name and different items listed.",
        "context": "CUSTOMER: Looking at the packing document in my shipment.\nBRAND: What information does the packing invoice display?\nCUSTOMER: The package had someone else's packing slip inside with a different name and different items listed.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "WRONG_ITEM_RECEIVED",
        "primary_intent": "WRONG_ITEM_RECEIVED",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Cross-customer shipment swap / wrong order delivered.",
        "category": "WRONG_ITEM",
    },

    # --- RETURN_PICKUP_ISSUE (10 cases) ---
    {
        "customer_message": "Courier failed to show up for scheduled return pickup today between 9am and 5pm. Nobody arrived.",
        "context": "CUSTOMER: Courier failed to show up for scheduled return pickup today between 9am and 5pm. Nobody arrived.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Missed doorstep return pickup appointment.",
        "category": "RETURN_PICKUP",
    },
    {
        "customer_message": "The driver came to collect my return but refused to take it because it wasn't boxed in a separate shipping carton.",
        "context": "CUSTOMER: Return pickup issue with UPS today.\nBRAND: What occurred when the driver arrived for pickup?\nCUSTOMER: The driver came to collect my return but refused to take it because it wasn't boxed in a separate shipping carton.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "CARRIER_ALREADY_CONTACTED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Driver packaging dispute on return collection.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "The return QR code provided on my app was rejected by the UPS Store clerk as invalid.",
        "context": "CUSTOMER: The return QR code provided on my app was rejected by the UPS Store clerk as invalid.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Invalid QR code at drop-off carrier location.",
        "category": "RETURN_PICKUP",
    },
    {
        "customer_message": "I have rescheduled this return pickup 3 times now and every day I stay home waiting and no one shows up!",
        "context": "CUSTOMER: Still waiting for pickup of return package.\nBRAND: How many times has pickup been scheduled for this return?\nCUSTOMER: I have rescheduled this return pickup 3 times now and every day I stay home waiting and no one shows up!",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Repeated failed return pickup attempts across three scheduling cycles.",
        "category": "REPEATED_FAILED_SUPPORT",
    },
    {
        "customer_message": "Can I change my return method from home pickup to drop-off at a Whole Foods locker?",
        "context": "CUSTOMER: Can I change my return method from home pickup to drop-off at a Whole Foods locker?",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Return drop-off method modification inquiry.",
        "category": "RETURN_PICKUP",
    },
    {
        "customer_message": "I already provided the return authorization code RMA-88910 in the previous chat, where is the courier driver?",
        "context": "CUSTOMER: Tracking my return pickup RMA-88910.\nBRAND: We are reviewing the return collection status.\nCUSTOMER: I already provided the return authorization code RMA-88910 in the previous chat, where is the courier driver?",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "DETAILS_ALREADY_PROVIDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer referencing previously provided return authorization code.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "How do I print the return mailing label if I don't own a home printer?",
        "context": "CUSTOMER: How do I print the return mailing label if I don't own a home printer?",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Label printing options for customers without printing equipment.",
        "category": "RETURN_PICKUP",
    },
    {
        "customer_message": "The courier picked up my return parcel on Monday but never handed me a physical receipt or tracking slip.",
        "context": "CUSTOMER: Return pickup was completed earlier this week.\nBRAND: Did the courier scan or provide confirmation at your door?\nCUSTOMER: The courier picked up my return parcel on Monday but never handed me a physical receipt or tracking slip.",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "CARRIER_ALREADY_CONTACTED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer spoke to pickup courier but lacks physical receipt documentation.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "I spoke to customer service more than 4 times about this failed return pickup and I keep getting told to wait another 24 hours!",
        "context": "CUSTOMER: My return pickup has failed again.\nBRAND: Have you contacted our support team regarding these pickup failures?\nCUSTOMER: I spoke to customer service more than 4 times about this failed return pickup and I keep getting told to wait another 24 hours!",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Repeated unresolved support interactions regarding carrier pickup failure.",
        "category": "REPEATED_FAILED_SUPPORT",
    },
    {
        "customer_message": "The return window closes in 2 days but the carrier has not shown up. Will I still be able to get my refund?",
        "context": "CUSTOMER: The return window closes in 2 days but the carrier has not shown up. Will I still be able to get my refund?",
        "status": "NORMAL",
        "areas": "RETURNS_AND_REPLACEMENTS",
        "intents": "RETURN_PICKUP_ISSUE",
        "primary_intent": "RETURN_PICKUP_ISSUE",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Impending return window expiration caused by carrier delays.",
        "category": "RETURN_PICKUP",
    },

    # --- REFUND_STATUS_INQUIRY (12 cases) ---
    {
        "customer_message": "My returned item was delivered back to Amazon return facility 6 days ago according to tracking. Why has my refund not initiated?",
        "context": "CUSTOMER: Checking status of return #114-8891023.\nBRAND: Did the carrier tracking show the package reached our return warehouse?\nCUSTOMER: My returned item was delivered back to Amazon return facility 6 days ago according to tracking. Why has my refund not initiated?",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer confirmed return delivery on carrier tracking.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "Cancelled my order 5 minutes after placing it, when will the pre-authorization hold disappear from my bank account?",
        "context": "CUSTOMER: Cancelled my order 5 minutes after placing it, when will the pre-authorization hold disappear from my bank account?",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Immediate cancellation bank hold timeline inquiry.",
        "category": "REFUND_STATUS",
    },
    {
        "customer_message": "The support agent told me on Nov 1st that refund would appear in 3-5 business days. Today is Nov 12th and my account still shows pending!",
        "context": "CUSTOMER: Following up on refund promised by agent.\nBRAND: What timeframe did our team specify for the funds to reflect?\nCUSTOMER: The support agent told me on Nov 1st that refund would appear in 3-5 business days. Today is Nov 12th and my account still shows pending!",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Advised bank processing timeframe exceeded.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "I contacted support 5 times regarding my missing refund, and every single agent gives me a different conflicting explanation!",
        "context": "CUSTOMER: I need to speak to someone with authority regarding ticket #49281.\nBRAND: Let us review your prior interactions.\nCUSTOMER: I contacted support 5 times regarding my missing refund, and every single agent gives me a different conflicting explanation!",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Five previous support interactions with conflicting advice on refund.",
        "category": "REPEATED_FAILED_SUPPORT",
    },
    {
        "customer_message": "Can I have my refund issued as Amazon gift card balance instead of original payment method?",
        "context": "CUSTOMER: Can I have my refund issued as Amazon gift card balance instead of original payment method?",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Refund payment destination preference inquiry.",
        "category": "REFUND_STATUS",
    },
    {
        "customer_message": "I already sent my bank statement proof showing no refund was credited. Can someone please look into this?",
        "context": "CUSTOMER: Need follow-up on refund for order 112-9901823.\nBRAND: Have you verified with your financial institution whether funds arrived?\nCUSTOMER: I already sent my bank statement proof showing no refund was credited. Can someone please look into this?",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "DETAILS_ALREADY_PROVIDED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Customer previously uploaded bank statement evidence.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "The refund receipt email says $45 was refunded, but the original item cost was $75. Why was $30 deducted?",
        "context": "CUSTOMER: The refund receipt email says $45 was refunded, but the original item cost was $75. Why was $30 deducted?",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Partial refund deduction / restocking fee query.",
        "category": "REFUND_STATUS",
    },
    {
        "customer_message": "My card that made the purchase was closed due to fraud. How do I redirect the refund to my new bank checking account?",
        "context": "CUSTOMER: Question regarding where my refund will be deposited.\nBRAND: Was the refund issued to your original method of payment?\nCUSTOMER: My card that made the purchase was closed due to fraud. How do I redirect the refund to my new bank checking account?",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Refund redirection for closed/cancelled card account.",
        "category": "REFUND_STATUS",
    },
    {
        "customer_message": "I have called support repeatedly for 3 weeks about this $350 refund. Each time I am told it is escalating to billing department but nothing happens!",
        "context": "CUSTOMER: Still unresolved return refund.\nBRAND: What has been the status over your previous support calls?\nCUSTOMER: I have called support repeatedly for 3 weeks about this $350 refund. Each time I am told it is escalating to billing department but nothing happens!",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Repeated failed support encounters across 3 weeks for significant refund sum.",
        "category": "REPEATED_FAILED_SUPPORT",
    },
    {
        "customer_message": "Tracking shows return was received by Amazon warehouse on Friday, but my order status still says 'Return started' instead of refunded.",
        "context": "CUSTOMER: Return delivery status inquiry.\nBRAND: Have you checked the return tracking link provided in your returns center?\nCUSTOMER: Tracking shows return was received by Amazon warehouse on Friday, but my order status still says 'Return started' instead of refunded.",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "TRACKING_ALREADY_CHECKED",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Warehouse receipt confirmed on tracking but portal state not updated.",
        "category": "CONVERSATIONAL_STATE",
    },
    {
        "customer_message": "Is there an RRN or ARN refund reference number you can provide so my credit union can trace the incoming deposit?",
        "context": "CUSTOMER: Is there an RRN or ARN refund reference number you can provide so my credit union can trace the incoming deposit?",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Bank tracer ARN number request.",
        "category": "REFUND_STATUS",
    },
    {
        "customer_message": "I spoke to customer service on chat, phone, and email across 6 attempts and nobody has resolved this missing $89 refund!",
        "context": "CUSTOMER: Formal complaint regarding missing refund.\nBRAND: We want to help resolve this for you right away.\nCUSTOMER: I spoke to customer service on chat, phone, and email across 6 attempts and nobody has resolved this missing $89 refund!",
        "status": "NORMAL",
        "areas": "REFUNDS_AND_BILLING",
        "intents": "REFUND_STATUS_INQUIRY",
        "primary_intent": "REFUND_STATUS_INQUIRY",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Six multi-channel failed support attempts on uncredited refund.",
        "category": "REPEATED_FAILED_SUPPORT",
    },
]
