"""Security and Account Login Cases for Golden V2.

Contains 28 cases:
- 18 High-Risk Escalation cases (unauthorized changes, account takeover, suspicious locks, failed recovery)
- 10 Normal Auto-Handle cases (routine password reset, OTP questions, login assistance without risk signals)
Includes balanced multi-turn conversations and single-turn inquiries.
"""

SECURITY_AND_LOGIN_CASES = [
    # --- 18 High-Risk Security Compromise & Lockout Cases ---
    {
        "customer_message": "Someone broke into my amazon account and ordered 3 iphones to an address in Texas! I live in Ohio! Please lock it down immediately!",
        "context": "CUSTOMER: Someone broke into my amazon account and ordered 3 iphones to an address in Texas! I live in Ohio! Please lock it down immediately!",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Unauthorized account access and fraudulent purchase.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "My email linked with Amazon was changed without my permission this morning. I didn't authorize this, help me recover it.",
        "context": "CUSTOMER: My email linked with Amazon was changed without my permission this morning. I didn't authorize this, help me recover it.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Unauthorized email change reported by user.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "i think my acct is compromised... got text saying password changed 10 mins ago but it wasnt me!!",
        "context": "CUSTOMER: Urgent, something wrong with my credentials.\nBRAND: What specific alert or notification did you receive?\nCUSTOMER: i think my acct is compromised... got text saying password changed 10 mins ago but it wasnt me!!",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Compromised account notification; password changed without user consent.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "help, suspicious account activity detected on my profile and now it says account is locked for safety.",
        "context": "CUSTOMER: Cannot access my Amazon account.\nBRAND: What message appears when you try to sign in?\nCUSTOMER: help, suspicious account activity detected on my profile and now it says account is locked for safety.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Suspicious activity lockout requiring specialist review.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "My account was locked because of suspicious activity. I went through the password reset loop three times and it still rejects my login.",
        "context": "CUSTOMER: My account was locked because of suspicious activity. I went through the password reset loop three times and it still rejects my login.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Account lock with failed password reset recovery loop.",
        "category": "ACCOUNT_LOCK_FAILED_RECOVERY",
    },
    {
        "customer_message": "I responded to the address verification email to unlock my account 5 days ago, but no reply and still locked out.",
        "context": "CUSTOMER: My account was put on hold last week.\nBRAND: Please reply to the account specialist verification email with requested proof.\nCUSTOMER: I responded to the address verification email to unlock my account 5 days ago, but no reply and still locked out.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Unresponsive account specialist verification email resulting in prolonged lockout.",
        "category": "ACCOUNT_LOCK_FAILED_RECOVERY",
    },
    {
        "customer_message": "Account hijacked! Hacker added their phone number as 2FA so I cannot receive the OTP codes anymore!",
        "context": "CUSTOMER: Account hijacked! Hacker added their phone number as 2FA so I cannot receive the OTP codes anymore!",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Account takeover with 2FA device modification.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "Someone accessed my account without authorization and placed orders using my saved Amazon gift card balance.",
        "context": "CUSTOMER: Someone accessed my account without authorization and placed orders using my saved Amazon gift card balance.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Unauthorized account access and balance misuse.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "im locked out after identity verification failed online. It says contact customer support specialist.",
        "context": "CUSTOMER: Trouble completing account verification.\nBRAND: What does the verification portal display?\nCUSTOMER: im locked out after identity verification failed online. It says contact customer support specialist.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Identity verification failure prompting specialist escalation.",
        "category": "ACCOUNT_LOCK_FAILED_RECOVERY",
    },
    {
        "customer_message": "I got an alert about an unauthorized login attempt from an unknown browser in Romania. Is my account safe?",
        "context": "CUSTOMER: Security question regarding recent login alert.\nBRAND: Did you receive an email regarding an unrecognized location?\nCUSTOMER: I got an alert about an unauthorized login attempt from an unknown browser in Romania. Is my account safe?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Unauthorized foreign login attempt alert.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "I never requested a password change, but got an email saying my password was updated successfully. What should I do right now?!",
        "context": "CUSTOMER: Urgent security issue.\nBRAND: Please let us know what happened.\nCUSTOMER: I never requested a password change, but got an email saying my password was updated successfully. What should I do right now?!",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Unsolicited password modification notice.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "My seller and buyer accounts were suspended due to alleged suspicious login patterns. I submitted government ID three days ago with zero feedback.",
        "context": "CUSTOMER: My seller and buyer accounts were suspended due to alleged suspicious login patterns. I submitted government ID three days ago with zero feedback.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Suspension after suspicious login with elapsed document review window.",
        "category": "ACCOUNT_LOCK_FAILED_RECOVERY",
    },
    {
        "customer_message": "someone changed both my primary email and secondary recovery phone number. I am completely locked out.",
        "context": "CUSTOMER: I cannot reset my password through normal means.\nBRAND: Are you able to receive the security code on your recovery phone?\nCUSTOMER: someone changed both my primary email and secondary recovery phone number. I am completely locked out.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Complete account takeover with recovery credentials replaced.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "Account has been placed on hold by the security department. Followed up twice by phone, still no access.",
        "context": "CUSTOMER: Account has been placed on hold by the security department. Followed up twice by phone, still no access.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Security hold with repeated unsuccessful phone follow-ups.",
        "category": "REPEATED_FAILED_SUPPORT",
    },
    {
        "customer_message": "My password reset worked, but immediately upon signing in it displays 'Account Locked: Suspicious order activity'.",
        "context": "CUSTOMER: Successfully completed password reset.\nBRAND: Please sign in with your updated password.\nCUSTOMER: My password reset worked, but immediately upon signing in it displays 'Account Locked: Suspicious order activity'.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Hard account lock persisting post-password reset.",
        "category": "ACCOUNT_LOCK_FAILED_RECOVERY",
    },
    {
        "customer_message": "I believe my account has been hacked, there are searches in my browsing history for items I never looked at.",
        "context": "CUSTOMER: I believe my account has been hacked, there are searches in my browsing history for items I never looked at.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Subtle compromise indicator with unauthorized profile activity.",
        "category": "ACCOUNT_SECURITY",
    },
    {
        "customer_message": "Cannot log in because Amazon says account locked. I already uploaded utility bill 4 times as requested by email.",
        "context": "CUSTOMER: Account blocked for verification.\nBRAND: Have you submitted proof of residence to the verification link?\nCUSTOMER: Cannot log in because Amazon says account locked. I already uploaded utility bill 4 times as requested by email.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "WAITING_WINDOW_EXCEEDED",
        "should_escalate": True,
        "escalation_reason": "REPEATED_FAILED_SUPPORT_ATTEMPTS",
        "notes": "Repeated document uploads for account unlock without resolution.",
        "category": "ACCOUNT_LOCK_FAILED_RECOVERY",
    },
    {
        "customer_message": "Received alert that someone added an unauthorized credit card to my Amazon wallet and placed a digital order.",
        "context": "CUSTOMER: Unauthorized activity alert received.\nBRAND: What transaction or card update was made?\nCUSTOMER: Received alert that someone added an unauthorized credit card to my Amazon wallet and placed a digital order.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": True,
        "escalation_reason": "ACCOUNT_SECURITY_COMPROMISE",
        "notes": "Wallet tampering and unauthorized digital checkout.",
        "category": "ACCOUNT_SECURITY",
    },

    # --- 10 Normal Auto-Handle Login & Password Inquiries (SHOULD NOT ESCALATE) ---
    {
        "customer_message": "I forgot my password, how can I request a password reset email?",
        "context": "CUSTOMER: I forgot my password, how can I request a password reset email?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Standard self-service password reset inquiry.",
        "category": "NORMAL_LOGIN",
    },
    {
        "customer_message": "Where do I update my login password in my Amazon mobile app settings?",
        "context": "CUSTOMER: Need to update account security settings.\nBRAND: You can manage your login credentials under Your Account.\nCUSTOMER: Where do I update my login password in my Amazon mobile app settings?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "General guidance on app settings password change.",
        "category": "NORMAL_LOGIN",
    },
    {
        "customer_message": "My password reset link expired after 15 minutes, can you tell me how to generate a new one?",
        "context": "CUSTOMER: My password reset link expired after 15 minutes, can you tell me how to generate a new one?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Expired token guidance; safe self-service procedure.",
        "category": "NORMAL_LOGIN",
    },
    {
        "customer_message": "I am not getting the two-step verification SMS on my mobile phone, is there another way to sign in?",
        "context": "CUSTOMER: Two-step verification prompt appeared.\nBRAND: Are you able to receive SMS on your registered phone?\nCUSTOMER: I am not getting the two-step verification SMS on my mobile phone, is there another way to sign in?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Routine two-step verification backup method inquiry.",
        "category": "NORMAL_LOGIN",
    },
    {
        "customer_message": "How do I turn on two-step verification to make my Amazon account more secure?",
        "context": "CUSTOMER: How do I turn on two-step verification to make my Amazon account more secure?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Proactive security feature setup guidance.",
        "category": "NORMAL_LOGIN",
    },
    {
        "customer_message": "Can I use an authenticator app instead of text messages for Amazon login codes?",
        "context": "CUSTOMER: Looking for 2FA options.\nBRAND: Amazon supports multiple two-step verification methods.\nCUSTOMER: Can I use an authenticator app instead of text messages for Amazon login codes?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Informational inquiry regarding authenticator app configuration.",
        "category": "NORMAL_LOGIN",
    },
    {
        "customer_message": "I want to change the primary email address on my account because I switched internet providers.",
        "context": "CUSTOMER: I want to change the primary email address on my account because I switched internet providers.",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Voluntary routine email update in account settings.",
        "category": "NORMAL_LOGIN",
    },
    {
        "customer_message": "Every time I clear cookies it asks me to enter a verification code from my email. Is this normal?",
        "context": "CUSTOMER: Frequent verification prompts on browser.\nBRAND: Security checks verify unrecognized browser sessions.\nCUSTOMER: Every time I clear cookies it asks me to enter a verification code from my email. Is this normal?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Standard browser session and cookie verification explanation.",
        "category": "NORMAL_LOGIN",
    },
    {
        "customer_message": "How do I sign out of all active devices currently logged into my Amazon account?",
        "context": "CUSTOMER: How do I sign out of all active devices currently logged into my Amazon account?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Device management and remote sign-out settings guidance.",
        "category": "NORMAL_LOGIN",
    },
    {
        "customer_message": "My keyboard caps lock was on so I typed the wrong password. Now it says wait 5 minutes to try again. Do I need to reset it?",
        "context": "CUSTOMER: Entered incorrect password.\nBRAND: Temporary pauses protect accounts from repeated rapid sign-in attempts.\nCUSTOMER: My keyboard caps lock was on so I typed the wrong password. Now it says wait 5 minutes to try again. Do I need to reset it?",
        "status": "NORMAL",
        "areas": "ACCOUNT_ACCESS_AND_SECURITY",
        "intents": "ACCOUNT_LOGIN_ISSUES",
        "primary_intent": "ACCOUNT_LOGIN_ISSUES",
        "state": "INITIAL_INQUIRY",
        "should_escalate": False,
        "escalation_reason": None,
        "notes": "Temporary rate-limit lockout due to accidental typo; routine reassurance.",
        "category": "NORMAL_LOGIN",
    },
]
